#ifndef __ERR_CODE__
#define __ERR_CODE__


#define BMD_LOG_ERR_DB_EXECUTE  -100
#define BMD_LOG_ERR_LO_GET      -101


#define BMD_LOG_ERR_ID_ABSENT -200

/*#define BMD_LOG_HASH_EQUAL 666*/
/*#define BMD_LOG_HASH_DIFFRENT 999*/
#define BMD_LOG_HASH_EQUAL 0
#define BMD_LOG_HASH_DIFFRENT 1

#define BMD_LOG_WEAK_HASH 501
#define BMD_LOG_STRONG_HASH 502
#define BMD_LOG_SIGN_NODE 503

#define BMD_LOG_MODIFICATION 1
#define BMD_LOG_HASH_L0_MODIFICATION 1
#define BMD_LOG_OTHER_HASH_LEVEL_MODIFICATION 1
#define BMD_LOG_VERIFICATION_FAILED -1
#define BMD_LOG_VERIFICATION_SUCCESS 0

#endif
