<definitions name="QueueManagerService" targetNamespace="http://queuemanager.messagerouter.unizeto.pl/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://queuemanager.messagerouter.unizeto.pl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 <types/>
 <message name="QueueManager_put">
  <part name="messageBody" type="xsd:string"/>
  <part name="messageType" type="xsd:string"/>
  <part name="messageSender" type="xsd:string"/>
 </message>
 <message name="QueueManager_putResponse">
  <part name="return" type="xsd:boolean"/>
 </message>
 <portType name="QueueManager">
  <operation name="put" parameterOrder="messageBody messageType messageSender">
   <input message="tns:QueueManager_put"/>
   <output message="tns:QueueManager_putResponse"/>
  </operation>
 </portType>
 <binding name="QueueManagerBinding" type="tns:QueueManager">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="put">
   <soap:operation soapAction=""/>
   <input>
    <soap:body namespace="http://queuemanager.messagerouter.unizeto.pl/" use="literal"/>
   </input>
   <output>
    <soap:body namespace="http://queuemanager.messagerouter.unizeto.pl/" use="literal"/>
   </output>
  </operation>
 </binding>
 <service name="QueueManagerService">
  <port binding="tns:QueueManagerBinding" name="QueueManagerPort">
   <soap:address location="http://192.168.156.209:8081/MessageRouter-Router/QueueManager"/>
  </port>
 </service>
</definitions>