/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ShmDictionaries"
 * 	found in "./dict_asn1.asn1"
 */

#ifndef	_ShmDict_H_
#define	_ShmDict_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OBJECT_IDENTIFIER.h>
#include <bmd/libbmdasn1_core/ANY.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ShmDict */
typedef struct ShmDict {
	OBJECT_IDENTIFIER_t	 dictType;
	ANY_t	 dictContent;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShmDict_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShmDict;

#ifdef __cplusplus
}
#endif

#endif	/* _ShmDict_H_ */
