/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ShmDictionaries"
 * 	found in "./dict_asn1.asn1"
 */

#ifndef	_ShmDl_H_
#define	_ShmDl_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ShmDlNode;

/* ShmDl */
typedef struct ShmDl {
	A_SEQUENCE_OF(struct ShmDlNode) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShmDl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShmDl;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/ShmDicts/ShmDlNode.h>

#endif	/* _ShmDl_H_ */
