/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BMDDatagram"
 * 	found in "bmd_datagram.asn1"
 * 	`asn1c -fcompound-names -S`
 */

#ifndef	_MetaDatas_H_
#define	_MetaDatas_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OCTET_STRING.h>
#include <bmd/libbmdasn1_core/INTEGER.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MetaDatas */
typedef struct MetaDatas {
	OCTET_STRING_t	 oids;
	struct MetaDatas__lenOfOids {
		A_SEQUENCE_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lenOfOids;
	OCTET_STRING_t	 datas;
	struct MetaDatas__lenOfDatas {
		A_SEQUENCE_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lenOfDatas;
	OCTET_STRING_t	 myIds;
	struct MetaDatas__lenOfMyIds {
		A_SEQUENCE_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lenOfMyIds;
	OCTET_STRING_t	 ownerIds;
	struct MetaDatas__lenOfOwnerIds {
		A_SEQUENCE_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lenOfOwnerIds;
	OCTET_STRING_t	 ownerTypes;
	struct MetaDatas__lenOfOwnerTypes {
		A_SEQUENCE_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lenOfOwnerTypes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MetaDatas_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetaDatas;

#ifdef __cplusplus
}
#endif

#endif	/* _MetaDatas_H_ */
