/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#ifndef	_AcceptablePolicySet_H_
#define	_AcceptablePolicySet_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/CertPolicyId.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AcceptablePolicySet */
typedef struct AcceptablePolicySet {
	A_SEQUENCE_OF(CertPolicyId_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcceptablePolicySet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcceptablePolicySet;

#ifdef __cplusplus
}
#endif

#endif	/* _AcceptablePolicySet_H_ */
