/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#ifndef	_AttributeTypeConstraints_H_
#define	_AttributeTypeConstraints_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/AttributeType.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeTypeConstraints */
typedef struct AttributeTypeConstraints {
	A_SEQUENCE_OF(AttributeType_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeTypeConstraints_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeTypeConstraints;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeTypeConstraints_H_ */
