/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#ifndef	_MandatedUnsignedAttr_H_
#define	_MandatedUnsignedAttr_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/SigPolicy/CMSAttrs.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MandatedUnsignedAttr */
typedef CMSAttrs_t	 MandatedUnsignedAttr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MandatedUnsignedAttr;
asn_struct_free_f MandatedUnsignedAttr_free;
asn_struct_print_f MandatedUnsignedAttr_print;
asn_constr_check_f MandatedUnsignedAttr_constraint;
ber_type_decoder_f MandatedUnsignedAttr_decode_ber;
der_type_encoder_f MandatedUnsignedAttr_encode_der;
xer_type_decoder_f MandatedUnsignedAttr_decode_xer;
xer_type_encoder_f MandatedUnsignedAttr_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MandatedUnsignedAttr_H_ */
