/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "SigPolicyID"
 * 	found in "ws.asn1"
 */

#ifndef	_OtherHashAlgAndValue_H_
#define	_OtherHashAlgAndValue_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/AlgorithmIdentifier.h>
#include <bmd/libbmdasn1_common/SigPolicy/OtherHashValue.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OtherHashAlgAndValue */
typedef struct OtherHashAlgAndValue {
	AlgorithmIdentifier_t	 hashAlgorithm;
	OtherHashValue_t	 hashValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OtherHashAlgAndValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OtherHashAlgAndValue;

#ifdef __cplusplus
}
#endif

#endif	/* _OtherHashAlgAndValue_H_ */
