/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#ifndef	_PathLenConstraint_H_
#define	_PathLenConstraint_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathLenConstraint */
typedef INTEGER_t	 PathLenConstraint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathLenConstraint;
asn_struct_free_f PathLenConstraint_free;
asn_struct_print_f PathLenConstraint_print;
asn_constr_check_f PathLenConstraint_constraint;
ber_type_decoder_f PathLenConstraint_decode_ber;
der_type_encoder_f PathLenConstraint_encode_der;
xer_type_decoder_f PathLenConstraint_decode_xer;
xer_type_encoder_f PathLenConstraint_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PathLenConstraint_H_ */
