/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#ifndef	_SignPolicyHash_H_
#define	_SignPolicyHash_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignPolicyHash */
typedef OCTET_STRING_t	 SignPolicyHash_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignPolicyHash;
asn_struct_free_f SignPolicyHash_free;
asn_struct_print_f SignPolicyHash_print;
asn_constr_check_f SignPolicyHash_constraint;
ber_type_decoder_f SignPolicyHash_decode_ber;
der_type_encoder_f SignPolicyHash_encode_der;
xer_type_decoder_f SignPolicyHash_decode_xer;
xer_type_encoder_f SignPolicyHash_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SignPolicyHash_H_ */
