/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#ifndef	_SigningCertTrustCondition_H_
#define	_SigningCertTrustCondition_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/SigPolicy/CertificateTrustTrees.h>
#include <bmd/libbmdasn1_common/SigPolicy/CertRevReq.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SigningCertTrustCondition */
typedef struct SigningCertTrustCondition {
	CertificateTrustTrees_t	 signerTrustTrees;
	CertRevReq_t	 signerRevReq;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SigningCertTrustCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigningCertTrustCondition;

#ifdef __cplusplus
}
#endif

#endif	/* _SigningCertTrustCondition_H_ */
