/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "SigPolicyID"
 * 	found in "ws.asn1"
 */

#ifndef	_SigPolicyQualifierInfo_H_
#define	_SigPolicyQualifierInfo_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/SigPolicy/SigPolicyQualifierId.h>
#include <bmd/libbmdasn1_core/ANY.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SigPolicyQualifierInfo */
typedef struct SigPolicyQualifierInfo {
	SigPolicyQualifierId_t	 sigPolicyQualifierId;
	ANY_t	 sigQualifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SigPolicyQualifierInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SigPolicyQualifierInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _SigPolicyQualifierInfo_H_ */
