/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "PKIX1Implicit88.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/pkcs15/CertId.h>

static asn_TYPE_member_t asn_MBR_CertId_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertId, issuer),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertId, serialNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serialNumber"
		},
};
static ber_tlv_tag_t asn_DEF_CertId_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CertId_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* serialNumber at 113 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* otherName at 168 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* rfc822Name at 169 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* dNSName at 170 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* x400Address at 171 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* directoryName at 172 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 0, 0, 0 }, /* ediPartyName at 173 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 }, /* uniformResourceIdentifier at 174 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 0, 0, 0 }, /* iPAddress at 175 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 0, 0, 0 } /* registeredID at 176 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CertId_specs_1 = {
	sizeof(struct CertId),
	offsetof(struct CertId, _asn_ctx),
	asn_MAP_CertId_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CertId = {
	"CertId",
	"CertId",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CertId_tags_1,
	sizeof(asn_DEF_CertId_tags_1)
		/sizeof(asn_DEF_CertId_tags_1[0]), /* 1 */
	asn_DEF_CertId_tags_1,	/* Same as above */
	sizeof(asn_DEF_CertId_tags_1)
		/sizeof(asn_DEF_CertId_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CertId_1,
	2,	/* Elements count */
	&asn_SPC_CertId_specs_1	/* Additional specs */
};

