/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "PKIX1Explicit88.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/pkcs15/PBKDF2-params.h>

static int
memb_iterationCount_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_consume_bytes_f *app_errlog, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_keyLength_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_consume_bytes_f *app_errlog, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_PBKDF2_params_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PBKDF2_params, salt),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_PKCS15Salt,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"salt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PBKDF2_params, iterationCount),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		memb_iterationCount_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iterationCount"
		},
	{ ATF_POINTER, 2, offsetof(struct PBKDF2_params, keyLength),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		memb_keyLength_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"keyLength"
		},
	{ ATF_POINTER, 1, offsetof(struct PBKDF2_params, prf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prf"
		},
};
static ber_tlv_tag_t asn_DEF_PBKDF2_params_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PBKDF2_params_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 1 }, /* iterationCount at 349 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -1, 0 }, /* keyLength at 350 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* specified at 343 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* otherSource at 345 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 } /* prf at 351 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PBKDF2_params_specs_1 = {
	sizeof(struct PBKDF2_params),
	offsetof(struct PBKDF2_params, _asn_ctx),
	asn_MAP_PBKDF2_params_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PBKDF2_params = {
	"PBKDF2-params",
	"PBKDF2-params",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PBKDF2_params_tags_1,
	sizeof(asn_DEF_PBKDF2_params_tags_1)
		/sizeof(asn_DEF_PBKDF2_params_tags_1[0]), /* 1 */
	asn_DEF_PBKDF2_params_tags_1,	/* Same as above */
	sizeof(asn_DEF_PBKDF2_params_tags_1)
		/sizeof(asn_DEF_PBKDF2_params_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PBKDF2_params_1,
	4,	/* Elements count */
	&asn_SPC_PBKDF2_params_specs_1	/* Additional specs */
};

