/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/pkcs15/PKCS15keyInfo.h>

static asn_TYPE_member_t asn_MBR_PKCS15keyInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PKCS15keyInfo, choice.recipientInfo),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_RecipientInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recipientInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PKCS15keyInfo, choice.passwordInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PKCS15PasswordInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"passwordInfo"
		},
};
static asn_TYPE_tag2member_t asn_MAP_PKCS15keyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* ktri at 148 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* passwordInfo at 303 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* kari at 149 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* kekri at 150 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* pwri at 151 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 } /* ori at 152 */
};
static asn_CHOICE_specifics_t asn_SPC_PKCS15keyInfo_specs_1 = {
	sizeof(struct PKCS15keyInfo),
	offsetof(struct PKCS15keyInfo, _asn_ctx),
	offsetof(struct PKCS15keyInfo, present),
	sizeof(((struct PKCS15keyInfo *)0)->present),
	asn_MAP_PKCS15keyInfo_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PKCS15keyInfo = {
	"PKCS15keyInfo",
	"PKCS15keyInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_PKCS15keyInfo_1,
	2,	/* Elements count */
	&asn_SPC_PKCS15keyInfo_specs_1	/* Additional specs */
};

