/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/pkcs15/PKCS15ReferencedValue.h>

static asn_TYPE_member_t asn_MBR_PKCS15ReferencedValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PKCS15ReferencedValue, choice.path),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PKCS15Path,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"path"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PKCS15ReferencedValue, choice.url),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_PKCS15URL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"url"
		},
};
static asn_TYPE_tag2member_t asn_MAP_PKCS15ReferencedValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* path at 71 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 1, 0, 0 }, /* url at 81 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 } /* urlWithDigest at 83 */
};
static asn_CHOICE_specifics_t asn_SPC_PKCS15ReferencedValue_specs_1 = {
	sizeof(struct PKCS15ReferencedValue),
	offsetof(struct PKCS15ReferencedValue, _asn_ctx),
	offsetof(struct PKCS15ReferencedValue, present),
	sizeof(((struct PKCS15ReferencedValue *)0)->present),
	asn_MAP_PKCS15ReferencedValue_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PKCS15ReferencedValue = {
	"PKCS15ReferencedValue",
	"PKCS15ReferencedValue",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_PKCS15ReferencedValue_1,
	2,	/* Elements count */
	&asn_SPC_PKCS15ReferencedValue_specs_1	/* Additional specs */
};

