/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonCertificateAttributes.h>

static asn_TYPE_member_t asn_MBR_identifiers_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PKCS15CredentialIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_identifiers_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_identifiers_specs_7 = {
	sizeof(struct PKCS15CommonCertificateAttributes__identifiers),
	offsetof(struct PKCS15CommonCertificateAttributes__identifiers, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_identifiers_7 = {
	"identifiers",
	"identifiers",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_identifiers_tags_7,
	sizeof(asn_DEF_identifiers_tags_7)
		/sizeof(asn_DEF_identifiers_tags_7[0]) - 1, /* 1 */
	asn_DEF_identifiers_tags_7,	/* Same as above */
	sizeof(asn_DEF_identifiers_tags_7)
		/sizeof(asn_DEF_identifiers_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_identifiers_7,
	1,	/* Single element */
	&asn_SPC_identifiers_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PKCS15CommonCertificateAttributes_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PKCS15CommonCertificateAttributes, iD),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_PKCS15Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iD"
		},
	{ ATF_POINTER, 8, offsetof(struct PKCS15CommonCertificateAttributes, authority),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"authority"
		},
	{ ATF_POINTER, 7, offsetof(struct PKCS15CommonCertificateAttributes, identifier),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PKCS15CredentialIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"identifier"
		},
	{ ATF_POINTER, 6, offsetof(struct PKCS15CommonCertificateAttributes, certHash),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OOBCertHash,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certHash"
		},
	{ ATF_POINTER, 5, offsetof(struct PKCS15CommonCertificateAttributes, trustedUsage),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PKCS15Usage,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trustedUsage"
		},
	{ ATF_POINTER, 4, offsetof(struct PKCS15CommonCertificateAttributes, identifiers),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_identifiers_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"identifiers"
		},
	{ ATF_POINTER, 3, offsetof(struct PKCS15CommonCertificateAttributes, implicitTrust),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"implicitTrust"
		},
	{ ATF_POINTER, 2, offsetof(struct PKCS15CommonCertificateAttributes, startDate),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"startDate"
		},
	{ ATF_POINTER, 1, offsetof(struct PKCS15CommonCertificateAttributes, endDate),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"endDate"
		},
};
static ber_tlv_tag_t asn_DEF_PKCS15CommonCertificateAttributes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PKCS15CommonCertificateAttributes_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, 0, 0 }, /* authority at 165 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* iD at 164 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* identifier at 166 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 7, 0, 0 }, /* startDate at 171 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 3, 0, 0 }, /* certHash at 167 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, 0, 0 }, /* trustedUsage at 168 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 5, 0, 0 }, /* identifiers at 169 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 6, 0, 0 }, /* implicitTrust at 170 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 8, 0, 0 } /* endDate at 172 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PKCS15CommonCertificateAttributes_specs_1 = {
	sizeof(struct PKCS15CommonCertificateAttributes),
	offsetof(struct PKCS15CommonCertificateAttributes, _asn_ctx),
	asn_MAP_PKCS15CommonCertificateAttributes_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PKCS15CommonCertificateAttributes = {
	"PKCS15CommonCertificateAttributes",
	"PKCS15CommonCertificateAttributes",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PKCS15CommonCertificateAttributes_tags_1,
	sizeof(asn_DEF_PKCS15CommonCertificateAttributes_tags_1)
		/sizeof(asn_DEF_PKCS15CommonCertificateAttributes_tags_1[0]), /* 1 */
	asn_DEF_PKCS15CommonCertificateAttributes_tags_1,	/* Same as above */
	sizeof(asn_DEF_PKCS15CommonCertificateAttributes_tags_1)
		/sizeof(asn_DEF_PKCS15CommonCertificateAttributes_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PKCS15CommonCertificateAttributes_1,
	9,	/* Elements count */
	&asn_SPC_PKCS15CommonCertificateAttributes_specs_1	/* Additional specs */
};

