/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "PKIX1Explicit88.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/pkcs15/RSAPrivateKey.h>

static asn_TYPE_member_t asn_MBR_RSAPrivateKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, modulus),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modulus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, publicExponent),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"publicExponent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, privateExponent),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"privateExponent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, prime1),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prime1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, prime2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prime2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, exponent1),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exponent1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, exponent2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exponent2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPrivateKey, coefficient),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"coefficient"
		},
};
static ber_tlv_tag_t asn_DEF_RSAPrivateKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RSAPrivateKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 8 }, /* version at 354 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 7 }, /* modulus at 355 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 6 }, /* publicExponent at 356 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -3, 5 }, /* privateExponent at 357 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -4, 4 }, /* prime1 at 358 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 5, -5, 3 }, /* prime2 at 359 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -6, 2 }, /* exponent1 at 360 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -7, 1 }, /* exponent2 at 361 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -8, 0 } /* coefficient at 363 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RSAPrivateKey_specs_1 = {
	sizeof(struct RSAPrivateKey),
	offsetof(struct RSAPrivateKey, _asn_ctx),
	asn_MAP_RSAPrivateKey_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RSAPrivateKey = {
	"RSAPrivateKey",
	"RSAPrivateKey",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RSAPrivateKey_tags_1,
	sizeof(asn_DEF_RSAPrivateKey_tags_1)
		/sizeof(asn_DEF_RSAPrivateKey_tags_1[0]), /* 1 */
	asn_DEF_RSAPrivateKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_RSAPrivateKey_tags_1)
		/sizeof(asn_DEF_RSAPrivateKey_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RSAPrivateKey_1,
	9,	/* Elements count */
	&asn_SPC_RSAPrivateKey_specs_1	/* Additional specs */
};

