#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <errno.h>
#include <sys/types.h>

char *GetErrorStr(int err_code)
{
	switch (err_code)
	{
		case -2001000 : return "Error in parsing kontrolki file"; break;
		case -2001001 : return "Error in getting client's clearance"; break;
		case -2001002 : return "Filename given in protocol is incorrect"; break;
		case -2001003 : return "Invalid additional metadata value"; break;
		case -2001004 : return "Invalid user metadata value"; break;
		case -2001005 : return "Invalid system metadata value"; break;
		case -2001006 : return "Invalid role given in protocol"; break;
		case -2001007 : return "Invalid oid of additional metadata"; break;
		case -2001008 : return "Invalid oid of user metadata"; break;
		case -2001009 : return "Invalid oid of system metadata"; break;
		case -2001010 : return "Error in checking client's clearence"; break;
		case -2001011 : return "Invalid client's clearence format"; break;
		case -2001012 : return "Error in getting group info from attribute certificate"; break;
		case -2001013 : return "Invalid clearance level to perform action with given resource"; break;
		case -2001014 : return "No group specified in client's attribute certificate"; break;
		case -2001015 : return "No group specified in user form"; break;
		case -2001016 : return "Invalid group source in user form (proper BMD))"; break;
		case -2001050 : return "Error in reading from server's cert_store directory"; break;
		case -2001051 : return "No cert's found in server's cert_store directory"; break;
		case -2001052 : return "Error in decoding login certificate"; break;
		case -2001053 : return "Login certificate invalid format"; break;
		case -2001054 : return "Error in loading certificate path cert's file"; break;
		case -2001055 : return "Error in verifying login cert with certificate path cert"; break;
		case -2001056 : return "Error in verifying login cert's cert path"; break;
		case -2001057 : return "Extension absent in server's crl list"; break;
		case -2001058 : return "Error in loading server's crl list file"; break;
		case -2001059 : return "No crl cert in server's crl list file"; break;
		case -2001060 : return "Error in decoding server's crl list certificate"; break;
		case -2001061 : return "Login certificate invalid - present on crl list"; break;
		case -2001062 : return "Login certificate invalid - out of date"; break;
		case -2001063 : return "Error in loading server's acl file"; break;
		case -2001064 : return "Invalid format of server's acl file"; break;
		case -2001065 : return "Login certificate failed"; break;
		case -2002001 : return "Invalid additional metadata value"; break;
		case -2002002 : return "Invalid system metadata value"; break;
		case -2002003 : return "Invalid user metadata value"; break;
		case -2002004 : return "Invalid pki metadata value"; break;
		case -2002005 : return "Invalid cases metadata value"; break;
		case -2002006 : return "No user metadata present"; break;
		case -2002007 : return "No system metadata present"; break;
		case -2002008 : return "No pki metadata present"; break;
		case -2002009 : return "Invalid additional metadata oid format"; break;
		case -2002010 : return "Invalid system metadata oid format"; break;
		case -2002011 : return "Invalid user metadata oid format"; break;
		case -2002012 : return "Invalid pki metadata oid format"; break;
		case -2003000 : return "Client's has no goup specified"; break;
		case -2004000 : return "Client's role not found in dictionary"; break;
		case -2004001 : return "Client's role does not permit login for somebody"; break;
		case -2004002 : return "Client's role does not permit action"; break;
		case -2004003 : return "Client's certificate not found in attributes.db"; break;
		case -2004004 : return "Client's clearance not found in attributes.db"; break;
		case -3001000 : return "Database error during delete action"; break;
		case -3001001 : return "File to delete not found"; break;
		case -3001002 : return "File's to delete lob not found"; break;
		case -3001003 : return "File's to delete symkey's lob not found"; break;
		case -3001004 : return "File's to delete signatures's lob not found"; break;
		case -3001005 : return "File's to delete timestamp's lob not found"; break;
		case -3002000 : return "Database error during get only file action"; break;
		case -3002001 : return "File to get not found"; break;
		case -3002002 : return "File's to get lob not found"; break;
		case -3002003 : return "File's to get symkey's lob not found"; break;
		case -3006000 : return "Database error during get file action in CGI mode"; break;
		case -3006001 : return "File to get not found in CGI mode"; break;
		case -3006002 : return "File's to get lob not found in CGI mode"; break;
		case -3006003 : return "File's to get symkey's lob not found in CGI mode"; break;
		case -3003000 : return "Database error during search action"; break;
		case -3003001 : return "Fatal database error during search action"; break;
		case -3003002 : return "Invalid query type in datagram"; break;
		case -3004000 : return "Database error during get metadata action"; break;
		case -3004001 : return "File to get metadata not found"; break;
		case -3004002 : return "File's to get metadata symkey's lob not found"; break;
		case -3005000 : return "Database error during get metadata action in CGI mode"; break;
		case -3005001 : return "File to get metadata not found in CGI mode"; break;
		case -3005002 : return "File's to get metadata symkey's lob not found in CGI mode"; break;
		case -3007000 : return "Database error during signature verification"; break;
		case -3007001 : return "File to verify signature not found"; break;
		case -3007002 : return "File's to verify signature lob not found"; break;
		case -3007003 : return "File's to verify signature symkey's lob not found"; break;
		case -3007004 : return "Signature to verify not found (file not signed)"; break;
		case -3007005 : return "Signature's lob to verify not found"; break;
		case -4001000 : return "Invalid format of id given in protocol"; break;
		case -5001000 : return "DVCS - invalid certificate"; break;
		case 5001001 : return "DVCS - certificate verified positively"; break;
		case 5001002 : return "DVCS - certificate verified conditionally"; break;
		case -5001003 : return "DVCS - invalid verification of login certificate"; break;
		case -5001004 : return "DVCS - invalid verification of certificate"; break;
		case -5002000 : return "DVCS - invalid verification of signature"; break;
		case 5002001 : return "DVCS - signature verified positively"; break;
		case 5002002 : return "DVCS - signature verified conditionally"; break;
		case 5002003 : return "DVCS - signature accepted exceptionally "; break;
		case -5002004 : return "DVCS - signature/data is absent"; break;
		case -5002005 : return "DVCS - DVCS service failure"; break;
		case -5002006 : return "DVCS - file to verify signature not found"; break;
		case -5003000 : return "DVCS - DVCS service failure while verifying signing signature"; break;
		case -5003001 : return "DVCS - invalid verification of signing signature"; break;
		case -5003002 : return "DVCS - signing signature is absent"; break;
		case -5003003 : return "DVCS - conditional verification of signing signature"; break;
		case 5003001 : return "DVCS - invalid verification of signing signature (file inserted conditionally)"; break;
		case 5003002 : return "DVCS - signing signature is absent (file inserted conditionally)"; break;
		case 5003003 : return "DVCS - conditional verification of signing signature  (file inserted conditionally)"; break;
		case -6001000 : return "Error in mail sending session"; break;
		case -6001001 : return "Error in smtp address configuration option"; break;
		case -6001002 : return "Error in mail template configuration option"; break;
		case -6001003 : return "Error in mail images configuration option"; break;
		case -6001004 : return "Error in einvoice mail title configuration option"; break;
		case -6001005 : return "Error in smime file configuration option"; break;
		case -6001006 : return "Error in smime file's password configuration option"; break;
		case -6001007 : return "Error in session plugin configuration structure"; break;
		case -6002000 : return "Invalid exact time format in conservate plugin configuration file"; break;
		case -6002001 : return "Exact time in conservate plugin configuration file not specified"; break;
		case -7001000 : return "Soap login certificate not specified in client request"; break;
		case -7001001 : return "Soap bmd initialization error"; break;
		case -7001002 : return "Soap bmd initialization error"; break;
		case -7001003 : return "Error in reading soap server configuration file"; break;
		case -7001004 : return "Error in setting soap server's login info"; break;
		case -7001005 : return "Error in setting soap server's login certificate"; break;
		case -7001006 : return "Error in setting bmd server's public key in soap server"; break;
		case -7001007 : return "Error in setting soap server client's login certificate"; break;
		case -7001008 : return "Error in login soap server to bmd server"; break;
		case -7001009 : return "Error in setting soap server login role"; break;
		case -7001011 : return "First parameter not specified"; break;
		case -7001012 : return "Second parameter not specified"; break;
		case -7001013 : return "Third parameter not specified"; break;
		case -7001014 : return "Fourth parameter not specified"; break;
		case -7001015 : return "Fifth parameter not specified"; break;
		case -7001016 : return "Sixth parameter not specified"; break;
		case -7001017 : return "Seventh parameter not specified"; break;
		case -7001018 : return "Eighth parameter not specified"; break;
		case -7001019 : return "Ninth parameter not specified"; break;
		case -7001020 : return "Error in binding soap server socket"; break;
		case -7001021 : return "Error in getting dtg from stgset in soap server"; break;
		case -7001025 : return "Temporary directory undefined in configuration file"; break;
		case -7001026 : return "Final filename undefined in client request"; break;
		case -7001027 : return "Temporary filename undefined in client request"; break;
		case -7001028 : return "Input file undefined in client request"; break;
		case -7001029 : return "Invalid 'from' or 'to' value in search request"; break;
		case -7001030 : return "Invalid file's id value in client request"; break;
		case -7001031 : return "Invalid file's property value in client request"; break;
		case -7001032 : return "Input signature undefined in client request"; break;
		case -7001033 : return "Error in getting current working directory"; break;
		case -7001034 : return "Error in creating temporary directory"; break;
		case -7001035 : return "Error in changing cwd to temporary directory"; break;
		case -7001036 : return "Error in getting xml file from archive"; break;
		case -7001037 : return "Error in generating or getting pdf file from archive"; break;
		case -7001038 : return "Error in openning temporary directory"; break;
		case -7001039 : return "Requested chunk not found"; break;
		case -7001040 : return "Invalid search operator in client request (LIKE, ILIKE, EXACT, EQUAL)"; break;
		case -7001041 : return "Invalid search logical operator in client request (OR, AND)"; break;
		case -7001043 : return "Invalid sort order in client request (ASC, DESC)"; break;
		case -7001044 : return "Invalid sort oid format in client request"; break;
		case -7001045 : return "Invalid transaction identifier in client request"; break;
		case -7001046 : return "Transaction timeout (no file found with given transaction id)"; break;
		case -7001047 : return "Undefined file hash in client request"; break;
		case -7001048 : return "Invalid file hash in client request"; break;
		case -7001100 : return "Lob transfer not finished properly"; break;
		case -7001101 : return "Invalid total filesize value"; break;
		case -7001102 : return "Invalid package number (count)"; break;
		case -7002000 : return "Error in opening compress source file"; break;
		case -7002001 : return "Error in opening compress destination file"; break;
		case -7002002 : return "Error in opening decompress source file"; break;
		case -7002003 : return "Error in opening decompress destination file"; break;
		case -7002004 : return "List of files to compress is empty"; break;
		case -7002005 : return "Compress output file not defined"; break;
		case -7003000 : return "Error in parsing xsl file during convertion to html"; break;
		case -7003001 : return "Error in parsing xml file during convertion to html"; break;
		case -7003002 : return "Error in applying stylesheet on xsl document"; break;
		case -7003003 : return "Error in saving result html file"; break;
		case -7003004 : return "Undefined xsl pattern in soap server configuration"; break;
		case -7003005 : return "Cannot open xml pattern file defined in soap server configuration"; break;
		case -8001000 : return "Error in connecting to archive remote host"; break;
		case -8001001 : return "Error in connecting to archive remote host (unresolved domain address)"; break;
		case -8001002 : return "Error in reading from socket"; break;
		case -8001003 : return "Error in writing to socket"; break;
		case -8001004 : return "Connection rejected by remote host"; break;
		case -8001005 : return "Net connection subsystem error"; break;
		case -8001006 : return "Net connection subsystem error"; break;
		case -8001007 : return "Net connection subsystem error"; break;
		case -8001008 : return "Net connection subsystem error"; break;
		case -8001009 : return "Net connection subsystem error"; break;
		case -9001000 : return "Functionality not implemented"; break;
		case -9001001 : return "Functionality not available"; break;
		case -9001002 : return "Operation failed"; break;
		case -9001003 : return "Inproper credentials"; break;
		case -9001004 : return "Randomize subsystem error"; break;
		case -9001005 : return "Operation already completed"; break;
		case -9001006 : return "Variables not initialized"; break;
		case -9001007 : return "Protocol error"; break;
		case -9001008 : return "Overflow error"; break;
		case -9001009 : return "Operation interrupted by user"; break;
		case -9001010 : return "Operation not allowed"; break;
		case -9001011 : return "Operation timeout"; break;
		case -9001012 : return "Operation failed on client's side"; break;
		case -9001013 : return "Disconected from server, please login again"; break;
		case -9001014 : return "Resource unavailable"; break;
		case -9001015 : return "Operation cancelled"; break;
		case -9001016 : return "Plugin no loaded"; break;
		case -9001017 : return "Protocol version incorrect"; break;
		case -9001018 : return "Lob transfer cancelled by client"; break;
		case -9001019 : return "File size is too big"; break;
		case -9001020 : return "Error in setting gen buf"; break;
		case -9001021 : return "Error in connecting to database"; break;
		case -9001023 : return "No user with given id found in database"; break;
		case -9002000 : return "Memory allocation error"; break;
		case -9002001 : return "Disk operation error"; break;
		case -9002002 : return "Invalid daata format"; break;
		case -9002003 : return "No data found with specified conditions"; break;
		case -9002004 : return "Data too big"; break;
		case -9002005 : return "Unefficient memory"; break;
		case -9002006 : return "Serial file error"; break;
		case -9003000 : return "Invalid first parameter value"; break;
		case -9003001 : return "Invalid second parameter value"; break;
		case -9003002 : return "Invalid third parameter value"; break;
		case -9003003 : return "Invalid fourth parameter value"; break;
		case -9003004 : return "Invalid fifth parameter value"; break;
		case -9003005 : return "Invalid sixth parameter value"; break;
		case -9003006 : return "Invalid seventh parameter value"; break;
		case -9003007 : return "Invalid eight parameter value"; break;
		case -9003008 : return "Invalid ninth parameter value"; break;
		case -9003009 : return "Invalid tenth parameter value"; break;
		case -9003010 : return "Too few arguments error"; break;
		case -9004000 : return "Error in PKI verification"; break;
		case -9004001 : return "Unable to sign data"; break;
		case -9004002 : return "Error in encypting data"; break;
		case -9004003 : return "Error in decrypting data"; break;
		case -9004004 : return "Error in hash verification"; break;
		case -9004005 : return "Public and private key mismatch"; break;
		case -9004006 : return "Error in signature verification"; break;
		case -9004007 : return "Incorect server's certificate"; break;
		case -9004008 : return "Error in getting CRL list"; break;
		case -9004009 : return "Error in creating internat BIO for gen buf"; break;
		case -9004011 : return "No certificates found in given file"; break;
		case -9004012 : return "No terminal unit certificates found in given file"; break;
		case -9004013 : return "Ivalid password for given certificate"; break;
		case -9004014 : return "Unknown file format"; break;
		case -9004015 : return "Given file is not a certificate"; break;
		case -9004016 : return "Invalid certification path chain"; break;
		case -9004017 : return "Error in initializing certification path"; break;
		case -9004018 : return "Invalid certification path directory"; break;
		case -9004019 : return "Error in getting certification path"; break;
		case -9004020 : return "Error in getting certificate's issuer"; break;
		case -9004022 : return "Private key error"; break;
		case -9004024 : return "Error in reading private key"; break;
		case -9004025 : return "Error in reading public key"; break;
		case -9004026 : return "Error in reading X509"; break;
		case -9004027 : return "Invalid certificate"; break;
		case -9004028 : return "OpenSSL error"; break;
		case -500 : return "Database mechanisms error"; break;
		case -501 : return "Error in executing database command"; break;
		case -502 : return "Database mechanisms error"; break;
		case -503 : return "Database mechanisms error"; break;
		case -504 : return "Database mechanisms error"; break;
		case -505 : return "Database mechanisms error"; break;
		case -506 : return "Database mechanisms error"; break;
		case -507 : return "Database fatal error"; break;
		case -508 : return "Database mechanisms error"; break;
		case -509 : return "Database mechanisms error"; break;
		case -510 : return "Error in creating large object"; break;
		case -511 : return "Error in opening large object"; break;
		case -512 : return "Database mechanisms error"; break;
		case -513 : return "No data found"; break;
		case -514 : return "Connection to database failed"; break;
		case -515 : return "Database mechanisms error"; break;
		case -516 : return "Connection with database lost"; break;
		case -517 : return "Invalid sql sqript"; break;
		default :	return "An error occured"; break;
	}
}

char *GetErrorMsg(int error_code)
{
		return GetErrorStr(error_code);
}

