/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "BMDGroup"
 * 	found in "bmdGroup.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/BMDGroup.h>

static asn_TYPE_member_t asn_MBR_levels_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BMDGroupPairList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_levels_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_levels_specs_4 = {
	sizeof(struct BMDGroup__levels),
	offsetof(struct BMDGroup__levels, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_levels_4 = {
	"levels",
	"levels",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_levels_tags_4,
	sizeof(asn_DEF_levels_tags_4)
		/sizeof(asn_DEF_levels_tags_4[0]), /* 1 */
	asn_DEF_levels_tags_4,	/* Same as above */
	sizeof(asn_DEF_levels_tags_4)
		/sizeof(asn_DEF_levels_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_levels_4,
	1,	/* Single element */
	&asn_SPC_levels_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BMDGroup_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BMDGroup, groupName),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"groupName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BMDGroup, groupNameOID),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"groupNameOID"
		},
	{ ATF_POINTER, 1, offsetof(struct BMDGroup, levels),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_levels_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"levels"
		},
};
static ber_tlv_tag_t asn_DEF_BMDGroup_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BMDGroup_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* groupName at 20 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 0 }, /* groupNameOID at 21 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* levels at 22 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BMDGroup_specs_1 = {
	sizeof(struct BMDGroup),
	offsetof(struct BMDGroup, _asn_ctx),
	asn_MAP_BMDGroup_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BMDGroup = {
	"BMDGroup",
	"BMDGroup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BMDGroup_tags_1,
	sizeof(asn_DEF_BMDGroup_tags_1)
		/sizeof(asn_DEF_BMDGroup_tags_1[0]), /* 1 */
	asn_DEF_BMDGroup_tags_1,	/* Same as above */
	sizeof(asn_DEF_BMDGroup_tags_1)
		/sizeof(asn_DEF_BMDGroup_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BMDGroup_1,
	3,	/* Elements count */
	&asn_SPC_BMDGroup_specs_1	/* Additional specs */
};

