/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXDVCS"
 * 	found in "dvcs.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/Data.h>

static int
memb_certs1_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_consume_bytes_f *app_errlog, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, app_errlog, app_key);
	} else {
		_ASN_ERRLOG(app_errlog, app_key,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_certs1_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TargetEtcChain,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_certs1_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_certs1_specs_4 = {
	sizeof(struct certs1),
	offsetof(struct certs1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_certs1_4 = {
	"certs1",
	"certs1",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_certs1_tags_4,
	sizeof(asn_DEF_certs1_tags_4)
		/sizeof(asn_DEF_certs1_tags_4[0]) - 1, /* 1 */
	asn_DEF_certs1_tags_4,	/* Same as above */
	sizeof(asn_DEF_certs1_tags_4)
		/sizeof(asn_DEF_certs1_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_certs1_4,
	1,	/* Single element */
	&asn_SPC_certs1_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Data_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.message),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"message"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.messageImprint),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DigestInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageImprint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.certs1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_certs1_4,
		memb_certs1_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certs1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.messageInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageInfo"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* message at 171 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* messageImprint at 172 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* certs1 at 173 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 } /* messageInfo at 175 */
};
static asn_CHOICE_specifics_t asn_SPC_Data_specs_1 = {
	sizeof(struct Data),
	offsetof(struct Data, _asn_ctx),
	offsetof(struct Data, present),
	sizeof(((struct Data *)0)->present),
	asn_MAP_Data_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Data = {
	"Data",
	"Data",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Data_1,
	4,	/* Elements count */
	&asn_SPC_Data_specs_1	/* Additional specs */
};

