/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "SecureMimeMessageV3"
 * 	found in "smimev3.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/RC2-CBC-parameter.h>

static asn_TYPE_member_t asn_MBR_RC2_CBC_parameter_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RC2_CBC_parameter, rc2ParameterVersion),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rc2ParameterVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RC2_CBC_parameter, iv),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_IV,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iv"
		},
};
static ber_tlv_tag_t asn_DEF_RC2_CBC_parameter_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RC2_CBC_parameter_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* rc2ParameterVersion at 75 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 } /* iv at 76 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RC2_CBC_parameter_specs_1 = {
	sizeof(struct RC2_CBC_parameter),
	offsetof(struct RC2_CBC_parameter, _asn_ctx),
	asn_MAP_RC2_CBC_parameter_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RC2_CBC_parameter = {
	"RC2-CBC-parameter",
	"RC2-CBC-parameter",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RC2_CBC_parameter_tags_1,
	sizeof(asn_DEF_RC2_CBC_parameter_tags_1)
		/sizeof(asn_DEF_RC2_CBC_parameter_tags_1[0]), /* 1 */
	asn_DEF_RC2_CBC_parameter_tags_1,	/* Same as above */
	sizeof(asn_DEF_RC2_CBC_parameter_tags_1)
		/sizeof(asn_DEF_RC2_CBC_parameter_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RC2_CBC_parameter_1,
	2,	/* Elements count */
	&asn_SPC_RC2_CBC_parameter_specs_1	/* Additional specs */
};

