/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/TSTInfo.h>

static asn_TYPE_member_t asn_MBR_TSTInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TSTInfo, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TSTInfo, policy),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_TSAPolicyId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"policy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TSTInfo, messageImprint),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MessageImprint,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageImprint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TSTInfo, serialNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serialNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TSTInfo, genTime),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"genTime"
		},
	{ ATF_POINTER, 5, offsetof(struct TSTInfo, accuracy),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Accuracy,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accuracy"
		},
	{ ATF_POINTER, 4, offsetof(struct TSTInfo, ordering),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ordering"
		},
	{ ATF_POINTER, 3, offsetof(struct TSTInfo, nonce),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonce"
		},
	{ ATF_POINTER, 2, offsetof(struct TSTInfo, tsa),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tsa"
		},
	{ ATF_POINTER, 1, offsetof(struct TSTInfo, extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Extensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensions"
		},
};
static ber_tlv_tag_t asn_DEF_TSTInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TSTInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 6, 0, 0 }, /* ordering at 146 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* version at 136 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 1 }, /* serialNumber at 141 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, -2, 0 }, /* nonce at 147 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* policy at 137 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* messageImprint at 138 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -1, 0 }, /* accuracy at 145 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 4, 0, 0 }, /* genTime at 144 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 8, 0, 0 }, /* tsa at 150 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 9, 0, 0 } /* extensions at 151 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TSTInfo_specs_1 = {
	sizeof(struct TSTInfo),
	offsetof(struct TSTInfo, _asn_ctx),
	asn_MAP_TSTInfo_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TSTInfo = {
	"TSTInfo",
	"TSTInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TSTInfo_tags_1,
	sizeof(asn_DEF_TSTInfo_tags_1)
		/sizeof(asn_DEF_TSTInfo_tags_1[0]), /* 1 */
	asn_DEF_TSTInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_TSTInfo_tags_1)
		/sizeof(asn_DEF_TSTInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TSTInfo_1,
	10,	/* Elements count */
	&asn_SPC_TSTInfo_specs_1	/* Additional specs */
};

