/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/SigPolicy/AlgorithmConstraintSet.h>

static asn_TYPE_member_t asn_MBR_AlgorithmConstraintSet_1[] = {
	{ ATF_POINTER, 5, offsetof(struct AlgorithmConstraintSet, signerAlgorithmConstraints),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmConstraints,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signerAlgorithmConstraints"
		},
	{ ATF_POINTER, 4, offsetof(struct AlgorithmConstraintSet, eeCertAlgorithmConstraints),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmConstraints,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eeCertAlgorithmConstraints"
		},
	{ ATF_POINTER, 3, offsetof(struct AlgorithmConstraintSet, caCertAlgorithmConstraints),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmConstraints,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"caCertAlgorithmConstraints"
		},
	{ ATF_POINTER, 2, offsetof(struct AlgorithmConstraintSet, aaCertAlgorithmConstraints),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmConstraints,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aaCertAlgorithmConstraints"
		},
	{ ATF_POINTER, 1, offsetof(struct AlgorithmConstraintSet, tsaCertAlgorithmConstraints),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlgorithmConstraints,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tsaCertAlgorithmConstraints"
		},
};
static ber_tlv_tag_t asn_DEF_AlgorithmConstraintSet_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AlgorithmConstraintSet_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* signerAlgorithmConstraints at 300 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eeCertAlgorithmConstraints at 302 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* caCertAlgorithmConstraints at 304 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aaCertAlgorithmConstraints at 306 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* tsaCertAlgorithmConstraints at 308 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AlgorithmConstraintSet_specs_1 = {
	sizeof(struct AlgorithmConstraintSet),
	offsetof(struct AlgorithmConstraintSet, _asn_ctx),
	asn_MAP_AlgorithmConstraintSet_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AlgorithmConstraintSet = {
	"AlgorithmConstraintSet",
	"AlgorithmConstraintSet",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AlgorithmConstraintSet_tags_1,
	sizeof(asn_DEF_AlgorithmConstraintSet_tags_1)
		/sizeof(asn_DEF_AlgorithmConstraintSet_tags_1[0]), /* 1 */
	asn_DEF_AlgorithmConstraintSet_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlgorithmConstraintSet_tags_1)
		/sizeof(asn_DEF_AlgorithmConstraintSet_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AlgorithmConstraintSet_1,
	5,	/* Elements count */
	&asn_SPC_AlgorithmConstraintSet_specs_1	/* Additional specs */
};

