/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/SigPolicy/AttributeTrustCondition.h>

static asn_TYPE_member_t asn_MBR_AttributeTrustCondition_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeTrustCondition, attributeMandated),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attributeMandated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeTrustCondition, howCertAttribute),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_HowCertAttribute,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"howCertAttribute"
		},
	{ ATF_POINTER, 3, offsetof(struct AttributeTrustCondition, attrCertificateTrustTrees),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CertificateTrustTrees,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attrCertificateTrustTrees"
		},
	{ ATF_POINTER, 2, offsetof(struct AttributeTrustCondition, attrRevReq),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CertRevReq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attrRevReq"
		},
	{ ATF_POINTER, 1, offsetof(struct AttributeTrustCondition, attributeConstraints),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AttributeConstraints,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attributeConstraints"
		},
};
static ber_tlv_tag_t asn_DEF_AttributeTrustCondition_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AttributeTrustCondition_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 0 }, /* attributeMandated at 275 */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 }, /* howCertAttribute at 277 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* attrCertificateTrustTrees at 278 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 }, /* attrRevReq at 279 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 4, 0, 0 } /* attributeConstraints at 280 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AttributeTrustCondition_specs_1 = {
	sizeof(struct AttributeTrustCondition),
	offsetof(struct AttributeTrustCondition, _asn_ctx),
	asn_MAP_AttributeTrustCondition_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AttributeTrustCondition = {
	"AttributeTrustCondition",
	"AttributeTrustCondition",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AttributeTrustCondition_tags_1,
	sizeof(asn_DEF_AttributeTrustCondition_tags_1)
		/sizeof(asn_DEF_AttributeTrustCondition_tags_1[0]), /* 1 */
	asn_DEF_AttributeTrustCondition_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttributeTrustCondition_tags_1)
		/sizeof(asn_DEF_AttributeTrustCondition_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AttributeTrustCondition_1,
	5,	/* Elements count */
	&asn_SPC_AttributeTrustCondition_specs_1	/* Additional specs */
};

