/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/SigPolicy/EnuRevReq.h>

int
EnuRevReq_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_consume_bytes_f *app_errlog, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, app_errlog, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
EnuRevReq_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

void
EnuRevReq_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	EnuRevReq_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
EnuRevReq_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	EnuRevReq_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
EnuRevReq_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	EnuRevReq_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
EnuRevReq_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	EnuRevReq_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
EnuRevReq_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	EnuRevReq_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
EnuRevReq_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	EnuRevReq_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_INTEGER_enum_map_t asn_MAP_EnuRevReq_value2enum_1[] = {
	{ 0,	8,	"clrCheck" },
	{ 1,	9,	"ocspCheck" },
	{ 2,	9,	"bothCheck" },
	{ 3,	11,	"eitherCheck" },
	{ 4,	7,	"noCheck" },
	{ 5,	5,	"other" }
};
static unsigned int asn_MAP_EnuRevReq_enum2value_1[] = {
	2,	/* bothCheck(2) */
	0,	/* clrCheck(0) */
	3,	/* eitherCheck(3) */
	4,	/* noCheck(4) */
	1,	/* ocspCheck(1) */
	5	/* other(5) */
};
static asn_INTEGER_specifics_t asn_SPC_EnuRevReq_specs_1 = {
	asn_MAP_EnuRevReq_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_EnuRevReq_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1	/* Strict enumeration */
};
static ber_tlv_tag_t asn_DEF_EnuRevReq_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EnuRevReq = {
	"EnuRevReq",
	"EnuRevReq",
	EnuRevReq_free,
	EnuRevReq_print,
	EnuRevReq_constraint,
	EnuRevReq_decode_ber,
	EnuRevReq_encode_der,
	EnuRevReq_decode_xer,
	EnuRevReq_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EnuRevReq_tags_1,
	sizeof(asn_DEF_EnuRevReq_tags_1)
		/sizeof(asn_DEF_EnuRevReq_tags_1[0]), /* 1 */
	asn_DEF_EnuRevReq_tags_1,	/* Same as above */
	sizeof(asn_DEF_EnuRevReq_tags_1)
		/sizeof(asn_DEF_EnuRevReq_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_EnuRevReq_specs_1	/* Additional specs */
};

