/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ETS-ElectronicSignaturePolicies-88syntax"
 * 	found in "rfc3125.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/SigPolicy/SigningPeriod.h>

static asn_TYPE_member_t asn_MBR_SigningPeriod_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SigningPeriod, notBefore),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notBefore"
		},
	{ ATF_POINTER, 1, offsetof(struct SigningPeriod, notAfter),
		(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)),
		0,
		&asn_DEF_GeneralizedTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notAfter"
		},
};
static ber_tlv_tag_t asn_DEF_SigningPeriod_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SigningPeriod_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 0, 0, 1 }, /* notBefore at 76 */
    { (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 1, -1, 0 } /* notAfter at 77 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SigningPeriod_specs_1 = {
	sizeof(struct SigningPeriod),
	offsetof(struct SigningPeriod, _asn_ctx),
	asn_MAP_SigningPeriod_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SigningPeriod = {
	"SigningPeriod",
	"SigningPeriod",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SigningPeriod_tags_1,
	sizeof(asn_DEF_SigningPeriod_tags_1)
		/sizeof(asn_DEF_SigningPeriod_tags_1[0]), /* 1 */
	asn_DEF_SigningPeriod_tags_1,	/* Same as above */
	sizeof(asn_DEF_SigningPeriod_tags_1)
		/sizeof(asn_DEF_SigningPeriod_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SigningPeriod_1,
	2,	/* Elements count */
	&asn_SPC_SigningPeriod_specs_1	/* Additional specs */
};

