/* bmd230ClientLib.c
   Generated by gSOAP 2.7.17 from ../bmdsoap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

/** Use this file in your project build instead of the two files bmd230C.c and bmd230Client.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "bmd230C.c"
#include "bmd230Client.c"

/* End of bmd230ClientLib.c */
