/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BMDDatagram"
 * 	found in "bmd_datagram.asn1"
 * 	`asn1c -fcompound-names -S`
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdpr/bmd_datagram/asn1clib/BMDDatagramSet.h>

static asn_TYPE_member_t asn_MBR_bmdDatagramsTable_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BMDDatagram,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_bmdDatagramsTable_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_bmdDatagramsTable_specs_2 = {
	sizeof(struct BMDDatagramSet__bmdDatagramsTable),
	offsetof(struct BMDDatagramSet__bmdDatagramsTable, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_bmdDatagramsTable_2 = {
	"bmdDatagramsTable",
	"bmdDatagramsTable",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_bmdDatagramsTable_tags_2,
	sizeof(asn_DEF_bmdDatagramsTable_tags_2)
		/sizeof(asn_DEF_bmdDatagramsTable_tags_2[0]) - 1, /* 1 */
	asn_DEF_bmdDatagramsTable_tags_2,	/* Same as above */
	sizeof(asn_DEF_bmdDatagramsTable_tags_2)
		/sizeof(asn_DEF_bmdDatagramsTable_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_bmdDatagramsTable_2,
	1,	/* Single element */
	&asn_SPC_bmdDatagramsTable_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BMDDatagramSet_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BMDDatagramSet, bmdDatagramsTable),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_bmdDatagramsTable_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bmdDatagramsTable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BMDDatagramSet, bmdDatagramsTransmissionCount),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bmdDatagramsTransmissionCount"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BMDDatagramSet, bmdDatagramsAllCount),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bmdDatagramsAllCount"
		},
};
static ber_tlv_tag_t asn_DEF_BMDDatagramSet_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BMDDatagramSet_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* bmdDatagramsTable at 11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* bmdDatagramsTransmissionCount at 12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* bmdDatagramsAllCount at 14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BMDDatagramSet_specs_1 = {
	sizeof(struct BMDDatagramSet),
	offsetof(struct BMDDatagramSet, _asn_ctx),
	asn_MAP_BMDDatagramSet_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BMDDatagramSet = {
	"BMDDatagramSet",
	"BMDDatagramSet",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BMDDatagramSet_tags_1,
	sizeof(asn_DEF_BMDDatagramSet_tags_1)
		/sizeof(asn_DEF_BMDDatagramSet_tags_1[0]), /* 1 */
	asn_DEF_BMDDatagramSet_tags_1,	/* Same as above */
	sizeof(asn_DEF_BMDDatagramSet_tags_1)
		/sizeof(asn_DEF_BMDDatagramSet_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BMDDatagramSet_1,
	3,	/* Elements count */
	&asn_SPC_BMDDatagramSet_specs_1	/* Additional specs */
};

