/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BMDDatagram"
 * 	found in "bmd_datagram.asn1"
 * 	`asn1c -fcompound-names -S`
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdpr/bmd_datagram/asn1clib/MetaDatas.h>

static asn_TYPE_member_t asn_MBR_lenOfOids_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_lenOfOids_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_lenOfOids_specs_3 = {
	sizeof(struct MetaDatas__lenOfOids),
	offsetof(struct MetaDatas__lenOfOids, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_lenOfOids_3 = {
	"lenOfOids",
	"lenOfOids",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_lenOfOids_tags_3,
	sizeof(asn_DEF_lenOfOids_tags_3)
		/sizeof(asn_DEF_lenOfOids_tags_3[0]), /* 1 */
	asn_DEF_lenOfOids_tags_3,	/* Same as above */
	sizeof(asn_DEF_lenOfOids_tags_3)
		/sizeof(asn_DEF_lenOfOids_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_lenOfOids_3,
	1,	/* Single element */
	&asn_SPC_lenOfOids_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_lenOfDatas_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_lenOfDatas_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_lenOfDatas_specs_6 = {
	sizeof(struct MetaDatas__lenOfDatas),
	offsetof(struct MetaDatas__lenOfDatas, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_lenOfDatas_6 = {
	"lenOfDatas",
	"lenOfDatas",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_lenOfDatas_tags_6,
	sizeof(asn_DEF_lenOfDatas_tags_6)
		/sizeof(asn_DEF_lenOfDatas_tags_6[0]), /* 1 */
	asn_DEF_lenOfDatas_tags_6,	/* Same as above */
	sizeof(asn_DEF_lenOfDatas_tags_6)
		/sizeof(asn_DEF_lenOfDatas_tags_6[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_lenOfDatas_6,
	1,	/* Single element */
	&asn_SPC_lenOfDatas_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_lenOfMyIds_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_lenOfMyIds_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_lenOfMyIds_specs_9 = {
	sizeof(struct MetaDatas__lenOfMyIds),
	offsetof(struct MetaDatas__lenOfMyIds, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_lenOfMyIds_9 = {
	"lenOfMyIds",
	"lenOfMyIds",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_lenOfMyIds_tags_9,
	sizeof(asn_DEF_lenOfMyIds_tags_9)
		/sizeof(asn_DEF_lenOfMyIds_tags_9[0]), /* 1 */
	asn_DEF_lenOfMyIds_tags_9,	/* Same as above */
	sizeof(asn_DEF_lenOfMyIds_tags_9)
		/sizeof(asn_DEF_lenOfMyIds_tags_9[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_lenOfMyIds_9,
	1,	/* Single element */
	&asn_SPC_lenOfMyIds_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_lenOfOwnerIds_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_lenOfOwnerIds_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_lenOfOwnerIds_specs_12 = {
	sizeof(struct MetaDatas__lenOfOwnerIds),
	offsetof(struct MetaDatas__lenOfOwnerIds, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_lenOfOwnerIds_12 = {
	"lenOfOwnerIds",
	"lenOfOwnerIds",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_lenOfOwnerIds_tags_12,
	sizeof(asn_DEF_lenOfOwnerIds_tags_12)
		/sizeof(asn_DEF_lenOfOwnerIds_tags_12[0]), /* 1 */
	asn_DEF_lenOfOwnerIds_tags_12,	/* Same as above */
	sizeof(asn_DEF_lenOfOwnerIds_tags_12)
		/sizeof(asn_DEF_lenOfOwnerIds_tags_12[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_lenOfOwnerIds_12,
	1,	/* Single element */
	&asn_SPC_lenOfOwnerIds_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_lenOfOwnerTypes_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_lenOfOwnerTypes_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_lenOfOwnerTypes_specs_15 = {
	sizeof(struct MetaDatas__lenOfOwnerTypes),
	offsetof(struct MetaDatas__lenOfOwnerTypes, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_lenOfOwnerTypes_15 = {
	"lenOfOwnerTypes",
	"lenOfOwnerTypes",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_lenOfOwnerTypes_tags_15,
	sizeof(asn_DEF_lenOfOwnerTypes_tags_15)
		/sizeof(asn_DEF_lenOfOwnerTypes_tags_15[0]), /* 1 */
	asn_DEF_lenOfOwnerTypes_tags_15,	/* Same as above */
	sizeof(asn_DEF_lenOfOwnerTypes_tags_15)
		/sizeof(asn_DEF_lenOfOwnerTypes_tags_15[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_lenOfOwnerTypes_15,
	1,	/* Single element */
	&asn_SPC_lenOfOwnerTypes_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MetaDatas_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, oids),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"oids"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, lenOfOids),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_lenOfOids_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lenOfOids"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, datas),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"datas"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, lenOfDatas),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_lenOfDatas_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lenOfDatas"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, myIds),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"myIds"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, lenOfMyIds),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_lenOfMyIds_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lenOfMyIds"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, ownerIds),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ownerIds"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, lenOfOwnerIds),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_lenOfOwnerIds_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lenOfOwnerIds"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, ownerTypes),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ownerTypes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaDatas, lenOfOwnerTypes),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_lenOfOwnerTypes_15,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lenOfOwnerTypes"
		},
};
static ber_tlv_tag_t asn_DEF_MetaDatas_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MetaDatas_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 4 }, /* oids at 43 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -1, 3 }, /* datas at 46 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, -2, 2 }, /* myIds at 49 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 6, -3, 1 }, /* ownerIds at 52 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 8, -4, 0 }, /* ownerTypes at 55 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 4 }, /* lenOfOids at 44 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 3 }, /* lenOfDatas at 47 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -2, 2 }, /* lenOfMyIds at 50 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -3, 1 }, /* lenOfOwnerIds at 53 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -4, 0 } /* lenOfOwnerTypes at 57 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MetaDatas_specs_1 = {
	sizeof(struct MetaDatas),
	offsetof(struct MetaDatas, _asn_ctx),
	asn_MAP_MetaDatas_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MetaDatas = {
	"MetaDatas",
	"MetaDatas",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MetaDatas_tags_1,
	sizeof(asn_DEF_MetaDatas_tags_1)
		/sizeof(asn_DEF_MetaDatas_tags_1[0]), /* 1 */
	asn_DEF_MetaDatas_tags_1,	/* Same as above */
	sizeof(asn_DEF_MetaDatas_tags_1)
		/sizeof(asn_DEF_MetaDatas_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MetaDatas_1,
	10,	/* Elements count */
	&asn_SPC_MetaDatas_specs_1	/* Additional specs */
};

