/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "BMDDatagram"
 * 	found in "bmd_datagram.asn1"
 * 	`asn1c -fcompound-names -S`
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdpr/bmd_datagram/asn1clib/MetaData.h>

static asn_TYPE_member_t asn_MBR_MetaData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MetaData, oid),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"oid"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct MetaData, data),
		(ber_tlv_tag_t)-1 /* Ambiguous tag (ANY?) TW Slabe miejsce ber_tlv_tag_t ma typ unsigned*/, 
		0,
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaData, myId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"myId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaData, ownerId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ownerId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetaData, ownerType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ownerType"
		},
};
static ber_tlv_tag_t asn_DEF_MetaData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MetaData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, 0, 2 }, /* myId at 43 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, -1, 1 }, /* ownerId at 44 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -2, 0 }, /* ownerType at 46 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* oid at 41 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MetaData_specs_1 = {
	sizeof(struct MetaData),
	offsetof(struct MetaData, _asn_ctx),
	asn_MAP_MetaData_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MetaData = {
	"MetaData",
	"MetaData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MetaData_tags_1,
	sizeof(asn_DEF_MetaData_tags_1)
		/sizeof(asn_DEF_MetaData_tags_1[0]), /* 1 */
	asn_DEF_MetaData_tags_1,	/* Same as above */
	sizeof(asn_DEF_MetaData_tags_1)
		/sizeof(asn_DEF_MetaData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MetaData_1,
	5,	/* Elements count */
	&asn_SPC_MetaData_specs_1	/* Additional specs */
};

