/* logClient.c
   Generated by gSOAP 2.7.17 from logsoap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "logH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) logClient.c ver 2.7.17 2010-11-05 08:33:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_log__logServerSend(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct log__logDatagram *logDatagram, long *result)
{	struct log__logServerSend soap_tmp_log__logServerSend;
	struct log__logServerSendResponse *soap_tmp_log__logServerSendResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://127.0.0.1:9999";
	soap->encodingStyle = NULL;
	soap_tmp_log__logServerSend.logDatagram = logDatagram;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_log__logServerSend(soap, &soap_tmp_log__logServerSend);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__logServerSend(soap, &soap_tmp_log__logServerSend, "log:logServerSend", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__logServerSend(soap, &soap_tmp_log__logServerSend, "log:logServerSend", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_long(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_log__logServerSendResponse = soap_get_log__logServerSendResponse(soap, NULL, "log:logServerSendResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_log__logServerSendResponse->result)
		*result = *soap_tmp_log__logServerSendResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_log__verifyLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, long logNode, long *result)
{	struct log__verifyLog soap_tmp_log__verifyLog;
	struct log__verifyLogResponse *soap_tmp_log__verifyLogResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://127.0.0.1:9999";
	soap->encodingStyle = NULL;
	soap_tmp_log__verifyLog.logNode = logNode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_log__verifyLog(soap, &soap_tmp_log__verifyLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__verifyLog(soap, &soap_tmp_log__verifyLog, "log:verifyLog", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__verifyLog(soap, &soap_tmp_log__verifyLog, "log:verifyLog", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_long(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_log__verifyLogResponse = soap_get_log__verifyLogResponse(soap, NULL, "log:verifyLogResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_log__verifyLogResponse->result)
		*result = *soap_tmp_log__verifyLogResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_log__verifyTree(struct soap *soap, const char *soap_endpoint, const char *soap_action, long signNode, long *result)
{	struct log__verifyTree soap_tmp_log__verifyTree;
	struct log__verifyTreeResponse *soap_tmp_log__verifyTreeResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://127.0.0.1:9999";
	soap->encodingStyle = NULL;
	soap_tmp_log__verifyTree.signNode = signNode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_log__verifyTree(soap, &soap_tmp_log__verifyTree);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__verifyTree(soap, &soap_tmp_log__verifyTree, "log:verifyTree", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__verifyTree(soap, &soap_tmp_log__verifyTree, "log:verifyTree", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_long(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_log__verifyTreeResponse = soap_get_log__verifyTreeResponse(soap, NULL, "log:verifyTreeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_log__verifyTreeResponse->result)
		*result = *soap_tmp_log__verifyTreeResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of logClient.c */
