/* logServer.c
   Generated by gSOAP 2.7.17 from logsoap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "logH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) logServer.c ver 2.7.17 2010-11-05 08:33:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 log_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || log_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 log_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "log:logServerSend"))
		return soap_serve_log__logServerSend(soap);
	if (!soap_match_tag(soap, soap->tag, "log:verifyLog"))
		return soap_serve_log__verifyLog(soap);
	if (!soap_match_tag(soap, soap->tag, "log:verifyTree"))
		return soap_serve_log__verifyTree(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_log__logServerSend(struct soap *soap)
{	struct log__logServerSend soap_tmp_log__logServerSend;
	struct log__logServerSendResponse soap_tmp_log__logServerSendResponse;
	long soap_tmp_long;
	soap_default_log__logServerSendResponse(soap, &soap_tmp_log__logServerSendResponse);
	soap_default_long(soap, &soap_tmp_long);
	soap_tmp_log__logServerSendResponse.result = &soap_tmp_long;
	soap_default_log__logServerSend(soap, &soap_tmp_log__logServerSend);
	soap->encodingStyle = NULL;
	if (!soap_get_log__logServerSend(soap, &soap_tmp_log__logServerSend, "log:logServerSend", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = log__logServerSend(soap, soap_tmp_log__logServerSend.logDatagram, &soap_tmp_long);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_log__logServerSendResponse(soap, &soap_tmp_log__logServerSendResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__logServerSendResponse(soap, &soap_tmp_log__logServerSendResponse, "log:logServerSendResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__logServerSendResponse(soap, &soap_tmp_log__logServerSendResponse, "log:logServerSendResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_log__verifyLog(struct soap *soap)
{	struct log__verifyLog soap_tmp_log__verifyLog;
	struct log__verifyLogResponse soap_tmp_log__verifyLogResponse;
	long soap_tmp_long;
	soap_default_log__verifyLogResponse(soap, &soap_tmp_log__verifyLogResponse);
	soap_default_long(soap, &soap_tmp_long);
	soap_tmp_log__verifyLogResponse.result = &soap_tmp_long;
	soap_default_log__verifyLog(soap, &soap_tmp_log__verifyLog);
	soap->encodingStyle = NULL;
	if (!soap_get_log__verifyLog(soap, &soap_tmp_log__verifyLog, "log:verifyLog", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = log__verifyLog(soap, soap_tmp_log__verifyLog.logNode, &soap_tmp_long);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_log__verifyLogResponse(soap, &soap_tmp_log__verifyLogResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__verifyLogResponse(soap, &soap_tmp_log__verifyLogResponse, "log:verifyLogResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__verifyLogResponse(soap, &soap_tmp_log__verifyLogResponse, "log:verifyLogResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_log__verifyTree(struct soap *soap)
{	struct log__verifyTree soap_tmp_log__verifyTree;
	struct log__verifyTreeResponse soap_tmp_log__verifyTreeResponse;
	long soap_tmp_long;
	soap_default_log__verifyTreeResponse(soap, &soap_tmp_log__verifyTreeResponse);
	soap_default_long(soap, &soap_tmp_long);
	soap_tmp_log__verifyTreeResponse.result = &soap_tmp_long;
	soap_default_log__verifyTree(soap, &soap_tmp_log__verifyTree);
	soap->encodingStyle = NULL;
	if (!soap_get_log__verifyTree(soap, &soap_tmp_log__verifyTree, "log:verifyTree", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = log__verifyTree(soap, soap_tmp_log__verifyTree.signNode, &soap_tmp_long);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_log__verifyTreeResponse(soap, &soap_tmp_log__verifyTreeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_log__verifyTreeResponse(soap, &soap_tmp_log__verifyTreeResponse, "log:verifyTreeResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_log__verifyTreeResponse(soap, &soap_tmp_log__verifyTreeResponse, "log:verifyTreeResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of logServer.c */
