/* soapStub.h
   Generated by gSOAP 2.7.9f from logsoap.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_ns__logDatagram
#define SOAP_TYPE_ns__logDatagram (7)
/* ns:logDatagram */
struct ns__logDatagram
{
	char *remoteHost;	/* optional element of type xsd:string */
	char *remotePort;	/* optional element of type xsd:string */
	char *srcFile;	/* optional element of type xsd:string */
	char *srcLine;	/* optional element of type xsd:string */
	char *srcFunction;	/* optional element of type xsd:string */
	char *logOwner;	/* optional element of type xsd:string */
	char *service;	/* optional element of type xsd:string */
	char *operationType;	/* optional element of type xsd:string */
	char *logLevel;	/* optional element of type xsd:string */
	char *dateTimeBegin;	/* optional element of type xsd:string */
	char *logString;	/* optional element of type xsd:string */
	char *logReason;	/* optional element of type xsd:string */
	char *logSolution;	/* optional element of type xsd:string */
	char *documentSize;	/* optional element of type xsd:string */
	char *documentFilename;	/* optional element of type xsd:string */
	char *logReferto;	/* optional element of type xsd:string */
	char *eventCode;	/* optional element of type xsd:string */
	char *logOwnerEventVisible;	/* optional element of type xsd:string */
	char *logRefertoEventVisible;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__logServerSendResponse
#define SOAP_TYPE_ns__logServerSendResponse (12)
/* ns:logServerSendResponse */
struct ns__logServerSendResponse
{
	long *result;	/* RPC return element */	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns__logServerSend
#define SOAP_TYPE_ns__logServerSend (13)
/* ns:logServerSend */
struct ns__logServerSend
{
	struct ns__logDatagram *logDatagram;	/* optional element of type ns:logDatagram */
};
#endif

#ifndef SOAP_TYPE_ns__verifyLogResponse
#define SOAP_TYPE_ns__verifyLogResponse (15)
/* ns:verifyLogResponse */
struct ns__verifyLogResponse
{
	long *result;	/* RPC return element */	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns__verifyLog
#define SOAP_TYPE_ns__verifyLog (16)
/* ns:verifyLog */
struct ns__verifyLog
{
	long logNode;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns__verifyTreeResponse
#define SOAP_TYPE_ns__verifyTreeResponse (18)
/* ns:verifyTreeResponse */
struct ns__verifyTreeResponse
{
	long *result;	/* RPC return element */	/* optional element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_ns__verifyTree
#define SOAP_TYPE_ns__verifyTree (19)
/* ns:verifyTree */
struct ns__verifyTree
{
	long signNode;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (22)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (23)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (25)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (26)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (27)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
typedef char *xsd__string;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__logServerSend(struct soap*, struct ns__logDatagram *logDatagram, long *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__verifyLog(struct soap*, long logNode, long *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__verifyTree(struct soap*, long signNode, long *result);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__logServerSend(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns__logDatagram *logDatagram, long *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__verifyLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, long logNode, long *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__verifyTree(struct soap *soap, const char *soap_endpoint, const char *soap_action, long signNode, long *result);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__logServerSend(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__verifyLog(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__verifyTree(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
