/* soapClient.c
   Generated by gSOAP 2.7.9f from logsoap.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.9f 2010-02-17 12:44:06 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__logServerSend(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns__logDatagram *logDatagram, long *result)
{	struct ns__logServerSend soap_tmp_ns__logServerSend;
	struct ns__logServerSendResponse *soap_tmp_ns__logServerSendResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://127.0.0.1:9999";
	soap->encodingStyle = NULL;
	soap_tmp_ns__logServerSend.logDatagram = logDatagram;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__logServerSend(soap, &soap_tmp_ns__logServerSend);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__logServerSend(soap, &soap_tmp_ns__logServerSend, "ns:logServerSend", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__logServerSend(soap, &soap_tmp_ns__logServerSend, "ns:logServerSend", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_long(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__logServerSendResponse = soap_get_ns__logServerSendResponse(soap, NULL, "ns:logServerSendResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__logServerSendResponse->result)
		*result = *soap_tmp_ns__logServerSendResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__verifyLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, long logNode, long *result)
{	struct ns__verifyLog soap_tmp_ns__verifyLog;
	struct ns__verifyLogResponse *soap_tmp_ns__verifyLogResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://127.0.0.1:9999";
	soap->encodingStyle = NULL;
	soap_tmp_ns__verifyLog.logNode = logNode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__verifyLog(soap, &soap_tmp_ns__verifyLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__verifyLog(soap, &soap_tmp_ns__verifyLog, "ns:verifyLog", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__verifyLog(soap, &soap_tmp_ns__verifyLog, "ns:verifyLog", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_long(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__verifyLogResponse = soap_get_ns__verifyLogResponse(soap, NULL, "ns:verifyLogResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__verifyLogResponse->result)
		*result = *soap_tmp_ns__verifyLogResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__verifyTree(struct soap *soap, const char *soap_endpoint, const char *soap_action, long signNode, long *result)
{	struct ns__verifyTree soap_tmp_ns__verifyTree;
	struct ns__verifyTreeResponse *soap_tmp_ns__verifyTreeResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://127.0.0.1:9999";
	soap->encodingStyle = NULL;
	soap_tmp_ns__verifyTree.signNode = signNode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__verifyTree(soap, &soap_tmp_ns__verifyTree);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__verifyTree(soap, &soap_tmp_ns__verifyTree, "ns:verifyTree", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__verifyTree(soap, &soap_tmp_ns__verifyTree, "ns:verifyTree", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_long(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__verifyTreeResponse = soap_get_ns__verifyTreeResponse(soap, NULL, "ns:verifyTreeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__verifyTreeResponse->result)
		*result = *soap_tmp_ns__verifyTreeResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
