/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15PrivateRSAKeyAttributes_H_
#define	_PKCS15PrivateRSAKeyAttributes_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15RSAPrivateKeyObjectValue.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKCS15RSAPrivateKeyInfo;

/* PKCS15PrivateRSAKeyAttributes */
typedef struct PKCS15PrivateRSAKeyAttributes {
	PKCS15RSAPrivateKeyObjectValue_t	 value;
	struct PKCS15RSAPrivateKeyInfo	*keyInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15PrivateRSAKeyAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15PrivateRSAKeyAttributes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15RSAPrivateKeyInfo.h>

#endif	/* _PKCS15PrivateRSAKeyAttributes_H_ */
