/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15CertificateValue_H_
#define	_PKCS15CertificateValue_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/Certificate.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKCS15CertificateValue */
typedef struct PKCS15CertificateValue {
	Certificate_t	 direct;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15CertificateValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15CertificateValue;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15CertificateValue_H_ */
