/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15PrivateRSAKeyObject_H_
#define	_PKCS15PrivateRSAKeyObject_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonObjectAttributes.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonKeyAttributes.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15PrivateRSAKeyAttributes.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKCS15CommonPrivateKeyAttributes;

/* PKCS15PrivateRSAKeyObject */
typedef struct PKCS15PrivateRSAKeyObject {
	PKCS15CommonObjectAttributes_t	 commonObjectAttributes;
	PKCS15CommonKeyAttributes_t	 classAttributes;
	struct PKCS15CommonPrivateKeyAttributes	*subClassAttributes	/* OPTIONAL */;
	PKCS15PrivateRSAKeyAttributes_t	 typeAttributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15PrivateRSAKeyObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15PrivateRSAKeyObject;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonPrivateKeyAttributes.h>

#endif	/* _PKCS15PrivateRSAKeyObject_H_ */
