/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15X509CertificateAttributes_H_
#define	_PKCS15X509CertificateAttributes_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CertificateValue.h>
#include <bmd/libbmdasn1_common/CertificateSerialNumber.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Name;

/* PKCS15X509CertificateAttributes */
typedef struct PKCS15X509CertificateAttributes {
	PKCS15CertificateValue_t	 value;
	struct Name	*subject	/* OPTIONAL */;
	struct Name	*issuer	/* OPTIONAL */;
	CertificateSerialNumber_t	*serialNumber	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15X509CertificateAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15X509CertificateAttributes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/Name.h>

#endif	/* _PKCS15X509CertificateAttributes_H_ */
