/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15CommonPrivateKeyAttributes_H_
#define	_PKCS15CommonPrivateKeyAttributes_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Name;
struct PKCS15CredentialIdentifier;

/* PKCS15CommonPrivateKeyAttributes */
typedef struct PKCS15CommonPrivateKeyAttributes {
	struct Name	*subjectName	/* OPTIONAL */;
	struct PKCS15CommonPrivateKeyAttributes__keyIdentifiers {
		A_SEQUENCE_OF(struct PKCS15CredentialIdentifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *keyIdentifiers;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15CommonPrivateKeyAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15CommonPrivateKeyAttributes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/Name.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CredentialIdentifier.h>

#endif	/* _PKCS15CommonPrivateKeyAttributes_H_ */
