/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15KeyAccessFlags_H_
#define	_PKCS15KeyAccessFlags_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKCS15KeyAccessFlags {
	PKCS15KeyAccessFlags_sensitive	= 0,
	PKCS15KeyAccessFlags_extractable	= 1,
	PKCS15KeyAccessFlags_alwaysSensitive	= 2,
	PKCS15KeyAccessFlags_neverExtractable	= 3,
	PKCS15KeyAccessFlags_local	= 4
} PKCS15KeyAccessFlags_e;

/* PKCS15KeyAccessFlags */
typedef BIT_STRING_t	 PKCS15KeyAccessFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15KeyAccessFlags;
asn_struct_free_f PKCS15KeyAccessFlags_free;
asn_struct_print_f PKCS15KeyAccessFlags_print;
asn_constr_check_f PKCS15KeyAccessFlags_constraint;
ber_type_decoder_f PKCS15KeyAccessFlags_decode_ber;
der_type_encoder_f PKCS15KeyAccessFlags_encode_der;
xer_type_decoder_f PKCS15KeyAccessFlags_decode_xer;
xer_type_encoder_f PKCS15KeyAccessFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15KeyAccessFlags_H_ */
