/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15RSAPrivateKeyObject_H_
#define	_PKCS15RSAPrivateKeyObject_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKCS15RSAPrivateKeyObject */
typedef struct PKCS15RSAPrivateKeyObject {
	INTEGER_t	*modulus	/* OPTIONAL */;
	INTEGER_t	*publicExponent	/* OPTIONAL */;
	INTEGER_t	*privateExponent	/* OPTIONAL */;
	INTEGER_t	*prime1	/* OPTIONAL */;
	INTEGER_t	*prime2	/* OPTIONAL */;
	INTEGER_t	*exponent1	/* OPTIONAL */;
	INTEGER_t	*exponent2	/* OPTIONAL */;
	INTEGER_t	*coefficient	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15RSAPrivateKeyObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15RSAPrivateKeyObject;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15RSAPrivateKeyObject_H_ */
