/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15CredentialIdentifier_H_
#define	_PKCS15CredentialIdentifier_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>
#include <bmd/libbmdasn1_core/ANY.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKCS15CredentialIdentifier */
typedef struct PKCS15CredentialIdentifier {
	INTEGER_t	 idType;
	ANY_t	 idValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15CredentialIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15CredentialIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15CredentialIdentifier_H_ */
