/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15ReferencedValue_H_
#define	_PKCS15ReferencedValue_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15Path.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15URL.h>
#include <bmd/libbmdasn1_core/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKCS15ReferencedValue_PR {
	PKCS15ReferencedValue_PR_NOTHING,	/* No components present */
	PKCS15ReferencedValue_PR_path,
	PKCS15ReferencedValue_PR_url,
} PKCS15ReferencedValue_PR;

/* PKCS15ReferencedValue */
typedef struct PKCS15ReferencedValue {
	PKCS15ReferencedValue_PR present;
	union PKCS15ReferencedValue_u {
		PKCS15Path_t	 path;
		PKCS15URL_t	 url;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15ReferencedValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15ReferencedValue;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15ReferencedValue_H_ */
