/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15Certificates_H_
#define	_PKCS15Certificates_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15Path.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15ReferencedValue.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15EnvelopedData.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKCS15Certificates_PR {
	PKCS15Certificates_PR_NOTHING,	/* No components present */
	PKCS15Certificates_PR_path,
	PKCS15Certificates_PR_objects,
	PKCS15Certificates_PR_indirect_protected,
	PKCS15Certificates_PR_direct_protected,
} PKCS15Certificates_PR;

/* Forward declarations */
struct PKCS15CertificateObject;

/* PKCS15Certificates */
typedef struct PKCS15Certificates {
	PKCS15Certificates_PR present;
	union PKCS15Certificates_u {
		PKCS15Path_t	 path;
		struct PKCS15Certificates__objects {
			A_SEQUENCE_OF(struct PKCS15CertificateObject) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} objects;
		PKCS15ReferencedValue_t	 indirect_protected;
		PKCS15EnvelopedData_t	 direct_protected;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15Certificates_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15Certificates;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CertificateObject.h>

#endif	/* _PKCS15Certificates_H_ */
