/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15CommonObjectAttributes_H_
#define	_PKCS15CommonObjectAttributes_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15Label.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonObjectFlags.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15Identifier.h>
#include <bmd/libbmdasn1_core/NativeInteger.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PKCS15AccessControlRule;

/* PKCS15CommonObjectAttributes */
typedef struct PKCS15CommonObjectAttributes {
	PKCS15Label_t	*label	/* OPTIONAL */;
	PKCS15CommonObjectFlags_t	*flags	/* OPTIONAL */;
	PKCS15Identifier_t	*authId	/* OPTIONAL */;
	long	*userConsent	/* OPTIONAL */;
	struct PKCS15CommonObjectAttributes__accessControlRules {
		A_SEQUENCE_OF(struct PKCS15AccessControlRule) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *accessControlRules;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15CommonObjectAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15CommonObjectAttributes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15AccessControlRule.h>

#endif	/* _PKCS15CommonObjectAttributes_H_ */
