/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15CertificateObject_H_
#define	_PKCS15CertificateObject_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonObjectAttributes.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15CommonCertificateAttributes.h>
#include <bmd/libbmdasn1_core/NULL.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15X509CertificateAttributes.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKCS15CertificateObject */
typedef struct PKCS15CertificateObject {
	PKCS15CommonObjectAttributes_t	 commonObjectAttributes;
	PKCS15CommonCertificateAttributes_t	 classAttributes;
	NULL_t	*subClassAttributes	/* OPTIONAL */;
	PKCS15X509CertificateAttributes_t	 typeAttributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15CertificateObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15CertificateObject;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15CertificateObject_H_ */
