/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "PKIX1Explicit88.asn1"
 */

#ifndef	_PKCS15Salt_H_
#define	_PKCS15Salt_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OCTET_STRING.h>
#include <bmd/libbmdasn1_common/AlgorithmIdentifier.h>
#include <bmd/libbmdasn1_core/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKCS15Salt_PR {
	PKCS15Salt_PR_NOTHING,	/* No components present */
	PKCS15Salt_PR_specified,
	PKCS15Salt_PR_otherSource,
} PKCS15Salt_PR;

/* PKCS15Salt */
typedef struct PKCS15Salt {
	PKCS15Salt_PR present;
	union PKCS15Salt_u {
		OCTET_STRING_t	 specified;
		AlgorithmIdentifier_t	 otherSource;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15Salt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15Salt;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15Salt_H_ */
