/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS-15"
 * 	found in "pkcs15_ms.asn1"
 */

#ifndef	_PKCS15RSAParamsAndOps_H_
#define	_PKCS15RSAParamsAndOps_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/NULL.h>
#include <bmd/libbmdasn1_common/pkcs15/PKCS15PublicKeyOperations.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKCS15RSAParamsAndOps */
typedef struct PKCS15RSAParamsAndOps {
	NULL_t	 parameters;
	PKCS15PublicKeyOperations_t	*supportedOperations	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKCS15RSAParamsAndOps_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKCS15RSAParamsAndOps;

#ifdef __cplusplus
}
#endif

#endif	/* _PKCS15RSAParamsAndOps_H_ */
