/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "ShmDictionaries"
 * 	found in "./dict_asn1.asn1"
 */

#include <bmd/libbmdasn1_core/asn_internal.h>

#include <bmd/libbmdasn1_common/ShmDicts/ShmRoleNodeDescr.h>

static asn_TYPE_member_t asn_MBR_roleActions_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_roleActions_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_roleActions_specs_4 = {
	sizeof(struct ShmRoleNodeDescr__roleActions),
	offsetof(struct ShmRoleNodeDescr__roleActions, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_roleActions_4 = {
	"roleActions",
	"roleActions",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_roleActions_tags_4,
	sizeof(asn_DEF_roleActions_tags_4)
		/sizeof(asn_DEF_roleActions_tags_4[0]), /* 1 */
	asn_DEF_roleActions_tags_4,	/* Same as above */
	sizeof(asn_DEF_roleActions_tags_4)
		/sizeof(asn_DEF_roleActions_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_roleActions_4,
	1,	/* Single element */
	&asn_SPC_roleActions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ShmRoleNodeDescr_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ShmRoleNodeDescr, roleId),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"roleId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ShmRoleNodeDescr, roleName),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"roleName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ShmRoleNodeDescr, roleActions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_roleActions_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"roleActions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ShmRoleNodeDescr, actionsCount),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"actionsCount"
		},
};
static ber_tlv_tag_t asn_DEF_ShmRoleNodeDescr_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ShmRoleNodeDescr_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, 0, 0 }, /* actionsCount at 14 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 1 }, /* roleId at 10 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 0 }, /* roleName at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 } /* roleActions at 12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ShmRoleNodeDescr_specs_1 = {
	sizeof(struct ShmRoleNodeDescr),
	offsetof(struct ShmRoleNodeDescr, _asn_ctx),
	asn_MAP_ShmRoleNodeDescr_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ShmRoleNodeDescr = {
	"ShmRoleNodeDescr",
	"ShmRoleNodeDescr",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0,	/* No PER decoder, -gen-PER to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ShmRoleNodeDescr_tags_1,
	sizeof(asn_DEF_ShmRoleNodeDescr_tags_1)
		/sizeof(asn_DEF_ShmRoleNodeDescr_tags_1[0]), /* 1 */
	asn_DEF_ShmRoleNodeDescr_tags_1,	/* Same as above */
	sizeof(asn_DEF_ShmRoleNodeDescr_tags_1)
		/sizeof(asn_DEF_ShmRoleNodeDescr_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ShmRoleNodeDescr_1,
	4,	/* Elements count */
	&asn_SPC_ShmRoleNodeDescr_specs_1	/* Additional specs */
};

