/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#ifndef	_Accuracy_H_
#define	_Accuracy_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>
#include <bmd/libbmdasn1_core/NativeInteger.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Accuracy */
typedef struct Accuracy {
	INTEGER_t	*seconds	/* OPTIONAL */;
	long	*millis	/* OPTIONAL */;
	long	*micros	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Accuracy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Accuracy;

#ifdef __cplusplus
}
#endif

#endif	/* _Accuracy_H_ */
