/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "ac1.asn1"
 */

#ifndef	_AttCertValidityPeriod_H_
#define	_AttCertValidityPeriod_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/GeneralizedTime.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttCertValidityPeriod */
typedef struct AttCertValidityPeriod {
	GeneralizedTime_t	 notBeforeTime;
	GeneralizedTime_t	 notAfterTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttCertValidityPeriod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttCertValidityPeriod;

#ifdef __cplusplus
}
#endif

#endif	/* _AttCertValidityPeriod_H_ */
