/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc3280-PKIX1Explicit88.asn1"
 */

#ifndef	_Attribute_H_
#define	_Attribute_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OBJECT_IDENTIFIER.h>
#include <bmd/libbmdasn1_common/AttributeValue.h>
#include <bmd/libbmdasn1_core/asn_SET_OF.h>
#include <bmd/libbmdasn1_core/constr_SET_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Attribute */
typedef struct Attribute {
	OBJECT_IDENTIFIER_t	 attrType;
	struct Attribute__attrValues {
		A_SET_OF(AttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} attrValues;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Attribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Attribute;

#ifdef __cplusplus
}
#endif

#endif	/* _Attribute_H_ */
