/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "BMDGroup"
 * 	found in "bmdGroup.asn1"
 */

#ifndef	_BMDGroups_H_
#define	_BMDGroups_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BMDGroup;

/* BMDGroups */
typedef struct BMDGroups {
	A_SEQUENCE_OF(struct BMDGroup) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BMDGroups_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BMDGroups;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/BMDGroup.h>

#endif	/* _BMDGroups_H_ */
