/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "SecureMimeMessageV3"
 * 	found in "smimev3.asn1"
 */

#ifndef	_CBCParameter_H_
#define	_CBCParameter_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/IV.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CBCParameter */
typedef IV_t	 CBCParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CBCParameter;
asn_struct_free_f CBCParameter_free;
asn_struct_print_f CBCParameter_print;
asn_constr_check_f CBCParameter_constraint;
ber_type_decoder_f CBCParameter_decode_ber;
der_type_encoder_f CBCParameter_encode_der;
xer_type_decoder_f CBCParameter_decode_xer;
xer_type_encoder_f CBCParameter_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CBCParameter_H_ */
