/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXDVCS"
 * 	found in "dvcs.asn1"
 */

#ifndef	_DVCSTime_H_
#define	_DVCSTime_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/GeneralizedTime.h>
#include <bmd/libbmdasn1_common/ContentInfo.h>
#include <bmd/libbmdasn1_core/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DVCSTime_PR {
	DVCSTime_PR_NOTHING,	/* No components present */
	DVCSTime_PR_genTime,
	DVCSTime_PR_timeStampToken,
} DVCSTime_PR;

/* DVCSTime */
typedef struct DVCSTime {
	DVCSTime_PR present;
	union DVCSTime_u {
		GeneralizedTime_t	 genTime;
		ContentInfo_t	 timeStampToken;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DVCSTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DVCSTime;

#ifdef __cplusplus
}
#endif

#endif	/* _DVCSTime_H_ */
