/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXDVCS"
 * 	found in "dvcs.asn1"
 */

#ifndef	_DVCSRequest_H_
#define	_DVCSRequest_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/DVCSRequestInformation.h>
#include <bmd/libbmdasn1_common/Data.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralName;

/* DVCSRequest */
typedef struct DVCSRequest {
	DVCSRequestInformation_t	 requestInformation;
	Data_t	 data;
	struct GeneralName	*transactionIdentifier	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DVCSRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DVCSRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/GeneralName.h>

#endif	/* _DVCSRequest_H_ */
