/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXDVCS"
 * 	found in "dvcs.asn1"
 */

#ifndef	_DVCSErrorNotice_H_
#define	_DVCSErrorNotice_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/PKIStatusInfo.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralName;

/* DVCSErrorNotice */
typedef struct DVCSErrorNotice {
	PKIStatusInfo_t	 transactionStatus;
	struct GeneralName	*transactionIdentifier	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DVCSErrorNotice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DVCSErrorNotice;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/GeneralName.h>

#endif	/* _DVCSErrorNotice_H_ */
