/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "rfc3852-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_ExtendedCertificate_H_
#define	_ExtendedCertificate_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/ExtendedCertificateInfo.h>
#include <bmd/libbmdasn1_common/SignatureAlgorithmIdentifier.h>
#include <bmd/libbmdasn1_common/Signature.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedCertificate */
typedef struct ExtendedCertificate {
	ExtendedCertificateInfo_t	 extendedCertificateInfo;
	SignatureAlgorithmIdentifier_t	 signatureAlgorithm;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedCertificate;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedCertificate_H_ */
