/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "ac1.asn1"
 */

#ifndef	_IssuerSerial_H_
#define	_IssuerSerial_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/GeneralNames.h>
#include <bmd/libbmdasn1_common/CertificateSerialNumber.h>
#include <bmd/libbmdasn1_common/UniqueIdentifier.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IssuerSerial */
typedef struct IssuerSerial {
	GeneralNames_t	 issuer;
	CertificateSerialNumber_t	 serial;
	UniqueIdentifier_t	*issuerUID	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IssuerSerial_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IssuerSerial;

#ifdef __cplusplus
}
#endif

#endif	/* _IssuerSerial_H_ */
