/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "SecureMimeMessageV3"
 * 	found in "smimev3.asn1"
 */

#ifndef	_IV_H_
#define	_IV_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IV */
typedef OCTET_STRING_t	 IV_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IV;
asn_struct_free_f IV_free;
asn_struct_print_f IV_print;
asn_constr_check_f IV_constraint;
ber_type_decoder_f IV_decode_ber;
der_type_encoder_f IV_encode_der;
xer_type_decoder_f IV_decode_xer;
xer_type_encoder_f IV_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IV_H_ */
