/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXDVCS"
 * 	found in "dvcs.asn1"
 */

#ifndef	_MessageInfo_H_
#define	_MessageInfo_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/OCTET_STRING.h>
#include <bmd/libbmdasn1_core/asn_SET_OF.h>
#include <bmd/libbmdasn1_core/constr_SET_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DigestInfo;

/* MessageInfo */
typedef struct MessageInfo {
	OCTET_STRING_t	 message;
	struct externalData {
		A_SET_OF(struct DigestInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} externalData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/DigestInfo.h>

#endif	/* _MessageInfo_H_ */
