/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXDVCS"
 * 	found in "dvcs.asn1"
 */

#ifndef	_Nonce_H_
#define	_Nonce_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Nonce */
typedef INTEGER_t	 Nonce_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Nonce;
asn_struct_free_f Nonce_free;
asn_struct_print_f Nonce_print;
asn_constr_check_f Nonce_constraint;
ber_type_decoder_f Nonce_decode_ber;
der_type_encoder_f Nonce_encode_der;
xer_type_decoder_f Nonce_decode_xer;
xer_type_encoder_f Nonce_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Nonce_H_ */
