/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "rfc3280-PKIX1Implicit88.asn1"
 */

#ifndef	_NoticeReference_H_
#define	_NoticeReference_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/DisplayText.h>
#include <bmd/libbmdasn1_core/INTEGER.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NoticeReference */
typedef struct NoticeReference {
	DisplayText_t	 organization;
	struct NoticeReference__noticeNumbers {
		A_SEQUENCE_OF(INTEGER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} noticeNumbers;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NoticeReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NoticeReference;

#ifdef __cplusplus
}
#endif

#endif	/* _NoticeReference_H_ */
