/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "ac1.asn1"
 */

#ifndef	_ObjectDigestInfo_H_
#define	_ObjectDigestInfo_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/ENUMERATED.h>
#include <bmd/libbmdasn1_core/OBJECT_IDENTIFIER.h>
#include <bmd/libbmdasn1_common/AlgorithmIdentifier.h>
#include <bmd/libbmdasn1_core/BIT_STRING.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectDigestInfo__digestedObjectType {
	ObjectDigestInfo__digestedObjectType_publicKey	= 0,
	ObjectDigestInfo__digestedObjectType_publicKeyCert	= 1,
	ObjectDigestInfo__digestedObjectType_otherObjectTypes	= 2
} ObjectDigestInfo__digestedObjectType_e;

/* ObjectDigestInfo */
typedef struct ObjectDigestInfo {
	ENUMERATED_t	 digestedObjectType;
	OBJECT_IDENTIFIER_t	*otherObjectTypeID	/* OPTIONAL */;
	AlgorithmIdentifier_t	 digestAlgorithm;
	BIT_STRING_t	 objectDigest;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectDigestInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_digestedObjectType_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ObjectDigestInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectDigestInfo_H_ */
