/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax"
 * 	found in "rfc3852-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_OriginatorPublicKey_H_
#define	_OriginatorPublicKey_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/AlgorithmIdentifier.h>
#include <bmd/libbmdasn1_core/BIT_STRING.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OriginatorPublicKey */
typedef struct OriginatorPublicKey {
	AlgorithmIdentifier_t	 algorithm;
	BIT_STRING_t	 publicKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatorPublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatorPublicKey;

#ifdef __cplusplus
}
#endif

#endif	/* _OriginatorPublicKey_H_ */
