/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#ifndef	_PKIFreeText_H_
#define	_PKIFreeText_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/UTF8String.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PKIFreeText */
typedef struct PKIFreeText {
	A_SEQUENCE_OF(UTF8String_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PKIFreeText_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIFreeText;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIFreeText_H_ */
