/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#ifndef	_PKIStatus_H_
#define	_PKIStatus_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PKIStatus {
	PKIStatus_granted	= 0,
	PKIStatus_grantedWithMods	= 1,
	PKIStatus_rejection	= 2,
	PKIStatus_waiting	= 3,
	PKIStatus_revocationWarning	= 4,
	PKIStatus_revocationNotification	= 5
} PKIStatus_e;

/* PKIStatus */
typedef INTEGER_t	 PKIStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PKIStatus;
asn_struct_free_f PKIStatus_free;
asn_struct_print_f PKIStatus_print;
asn_constr_check_f PKIStatus_constraint;
ber_type_decoder_f PKIStatus_decode_ber;
der_type_encoder_f PKIStatus_encode_der;
xer_type_decoder_f PKIStatus_decode_xer;
xer_type_encoder_f PKIStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PKIStatus_H_ */
