/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "rfc3280-PKIX1Implicit88.asn1"
 */

#ifndef	_PrivateKeyUsagePeriod_H_
#define	_PrivateKeyUsagePeriod_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/GeneralizedTime.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PrivateKeyUsagePeriod */
typedef struct PrivateKeyUsagePeriod {
	GeneralizedTime_t	*notBefore	/* OPTIONAL */;
	GeneralizedTime_t	*notAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrivateKeyUsagePeriod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivateKeyUsagePeriod;

#ifdef __cplusplus
}
#endif

#endif	/* _PrivateKeyUsagePeriod_H_ */
