/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "ocsp.asn1"
 */

#ifndef	_RevokedInfo_H_
#define	_RevokedInfo_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/GeneralizedTime.h>
#include <bmd/libbmdasn1_common/CRLReason.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RevokedInfo */
typedef struct RevokedInfo {
	GeneralizedTime_t	 revocationTime;
	CRLReason_t	*revocationReason	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevokedInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevokedInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _RevokedInfo_H_ */
