/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc3280-PKIX1Explicit88.asn1"
 */

#ifndef	_TBSCertificate_H_
#define	_TBSCertificate_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/Version.h>
#include <bmd/libbmdasn1_common/CertificateSerialNumber.h>
#include <bmd/libbmdasn1_common/AlgorithmIdentifier.h>
#include <bmd/libbmdasn1_common/Name.h>
#include <bmd/libbmdasn1_common/Validity.h>
#include <bmd/libbmdasn1_common/SubjectPublicKeyInfo.h>
#include <bmd/libbmdasn1_common/UniqueIdentifier.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Extensions;

/* TBSCertificate */
typedef struct TBSCertificate {
	Version_t	*version	/* DEFAULT 0 */;
	CertificateSerialNumber_t	 serialNumber;
	AlgorithmIdentifier_t	 signature;
	Name_t	 issuer;
	Validity_t	 validity;
	Name_t	 subject;
	SubjectPublicKeyInfo_t	 subjectPublicKeyInfo;
	UniqueIdentifier_t	*issuerUniqueID	/* OPTIONAL */;
	UniqueIdentifier_t	*subjectUniqueID	/* OPTIONAL */;
	struct Extensions	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TBSCertificate;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/Extensions.h>

#endif	/* _TBSCertificate_H_ */
