/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "rfc3280-PKIX1Explicit88.asn1"
 */

#ifndef	_TBSCertList_H_
#define	_TBSCertList_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/Version.h>
#include <bmd/libbmdasn1_common/AlgorithmIdentifier.h>
#include <bmd/libbmdasn1_common/Name.h>
#include <bmd/libbmdasn1_common/Time.h>
#include <bmd/libbmdasn1_core/asn_SEQUENCE_OF.h>
#include <bmd/libbmdasn1_common/CertificateSerialNumber.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Time;
struct Extensions;

typedef struct TBSCertList__revokedCertificates__Member {
	CertificateSerialNumber_t	 userCertificate;
	Time_t	 revocationDate;
	struct Extensions	*crlEntryExtensions	/* OPTIONAL */;
			
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSCertList__revokedCertificates__Member_t;

typedef struct TBSCertList__revokedCertificates {
	A_SEQUENCE_OF(TBSCertList__revokedCertificates__Member_t) list;
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSCertList__revokedCertificates_t;

/* TBSCertList */
typedef struct TBSCertList {
	Version_t	*version	/* OPTIONAL */;
	AlgorithmIdentifier_t	 signature;
	Name_t	 issuer;
	Time_t	 thisUpdate;
	struct Time	*nextUpdate	/* OPTIONAL */;
	TBSCertList__revokedCertificates_t *revokedCertificates;
	struct Extensions	*crlExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBSCertList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TBSCertList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/Time.h>
#include <bmd/libbmdasn1_common/Extensions.h>

#endif	/* _TBSCertList_H_ */
