/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#ifndef	_TimeStampToken_H_
#define	_TimeStampToken_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/ContentInfo.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeStampToken */
typedef ContentInfo_t	 TimeStampToken_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeStampToken;
asn_struct_free_f TimeStampToken_free;
asn_struct_print_f TimeStampToken_print;
asn_constr_check_f TimeStampToken_constraint;
ber_type_decoder_f TimeStampToken_decode_ber;
der_type_encoder_f TimeStampToken_encode_der;
xer_type_decoder_f TimeStampToken_decode_xer;
xer_type_encoder_f TimeStampToken_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeStampToken_H_ */
