/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#ifndef	_TimeStampResp_H_
#define	_TimeStampResp_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_common/PKIStatusInfo.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ContentInfo;

/* TimeStampResp */
typedef struct TimeStampResp {
	PKIStatusInfo_t	 status;
	struct ContentInfo	*timeStampToken	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeStampResp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimeStampResp;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/TimeStampToken.h>

#endif	/* _TimeStampResp_H_ */
