/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXTSP"
 * 	found in "tsp.asn1"
 */

#ifndef	_TSTInfo_H_
#define	_TSTInfo_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/INTEGER.h>
#include <bmd/libbmdasn1_common/TSAPolicyId.h>
#include <bmd/libbmdasn1_common/MessageImprint.h>
#include <bmd/libbmdasn1_core/GeneralizedTime.h>
#include <bmd/libbmdasn1_core/BOOLEAN.h>
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TSTInfo__version {
	TSTInfo__version_v1	= 1
} TSTInfo__version_e;

/* Forward declarations */
struct Accuracy;
struct GeneralName;
struct Extensions;

/* TSTInfo */
typedef struct TSTInfo {
	INTEGER_t	 version;
	TSAPolicyId_t	 policy;
	MessageImprint_t	 messageImprint;
	INTEGER_t	 serialNumber;
	GeneralizedTime_t	 genTime;
	struct Accuracy	*accuracy	/* OPTIONAL */;
	BOOLEAN_t	*ordering	/* DEFAULT FALSE */;
	INTEGER_t	*nonce	/* OPTIONAL */;
	struct GeneralName	*tsa	/* OPTIONAL */;
	struct Extensions	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TSTInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TSTInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/Accuracy.h>
#include <bmd/libbmdasn1_common/GeneralName.h>
#include <bmd/libbmdasn1_common/Extensions.h>

#endif	/* _TSTInfo_H_ */
