/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "OCSP"
 * 	found in "ocsp.asn1"
 */

#ifndef	_UnknownInfo_H_
#define	_UnknownInfo_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnknownInfo */
typedef NULL_t	 UnknownInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnknownInfo;
asn_struct_free_f UnknownInfo_free;
asn_struct_print_f UnknownInfo_print;
asn_constr_check_f UnknownInfo_constraint;
ber_type_decoder_f UnknownInfo_decode_ber;
der_type_encoder_f UnknownInfo_encode_der;
xer_type_decoder_f UnknownInfo_decode_xer;
xer_type_encoder_f UnknownInfo_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnknownInfo_H_ */
