/*
 * Generated by asn1c-0.9.20 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "ac1.asn1"
 */

#ifndef	_V2Form_H_
#define	_V2Form_H_


#include <bmd/libbmdasn1_core/asn_application.h>

/* Including external dependencies */
#include <bmd/libbmdasn1_core/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralNames;
struct IssuerSerial;
struct ObjectDigestInfo;

/* V2Form */
typedef struct V2Form {
	struct GeneralNames	*issuerName	/* OPTIONAL */;
	struct IssuerSerial	*baseCertificateID	/* OPTIONAL */;
	struct ObjectDigestInfo	*objectDigestInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2Form_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2Form;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <bmd/libbmdasn1_common/GeneralNames.h>
#include <bmd/libbmdasn1_common/IssuerSerial.h>
#include <bmd/libbmdasn1_common/ObjectDigestInfo.h>

#endif	/* _V2Form_H_ */
