#!/bin/sh

#this compiles asn1 modules using asn1c compiler
#ASN1_OPTIONS=-Werror -Wdebug-lexer
asn1c -Werror -fcompound-names rfc3369-CryptographicMessageSyntax.asn1 rfc3369-AttributeCertificateVersion1.asn1 rfc3281-PKIXAttributeCertificate.asn1 rfc3280-PKIX1Explicit88.asn1 rfc3280-PKIX1Implicit88.asn1
